`This notebook shows how to load and inspect the datasets.`

`Data validation is conducted through the Pydantic schemas when loading the data.`

In [1]:
import sys
import os

parent_dir = os.path.abspath("../")
sys.path.append(parent_dir)

import polars as pl
from chronoindex.dataset_loader import load_datasets

Load the raw data. Any validation message at this step indicates unexpected data structures; subjects that fail validation are skipped and not instantiated in the dataset.

In [2]:
datasets, errors = load_datasets(
    config_path= "datasets.toml",
    only=["aleppo","colas","zhao"] # To load all datasets at once, comment this line
)
if errors:
    raise RuntimeError(errors)

➡️ Loading datasets.aleppo
➡️ Loading datasets.colas
➡️ Loading datasets.zhao

## Aleppo (2017)

In [3]:
aleppo_dataset = datasets["aleppo"]

In [4]:
print("metadata shape:", aleppo_dataset.metadata.shape)
print("cgm_data shape:", aleppo_dataset.cgm_data.shape)
print("joined_data shape:", aleppo_dataset.joined_data.shape)

metadata shape: (226, 13)
cgm_data shape: (226, 5)
joined_data shape: (226, 10)

Inspect Main Output

In [5]:
aleppo_dataset.cgm_data

shape: (226, 5)
┌──────┬───────────────────────┬──────────────────────┬──────────────────────┬─────────────────────┐
│ PtID ┆ glucemia_series       ┆ time_series          ┆ time_series_internal ┆ days_from_enroll    │
│ ---  ┆ ---                   ┆ ---                  ┆ ---                  ┆ ---                 │
│ i32  ┆ list[f64]             ┆ list[time]           ┆ list[time]           ┆ list[i64]           │
╞══════╪═══════════════════════╪══════════════════════╪══════════════════════╪═════════════════════╡
│ 263  ┆ [89.0, 87.0, … 159.0] ┆ [03:11:00, 03:16:00, ┆ [null, null, …       ┆ [-138, -138, … 270] │
│      ┆                       ┆ … 11:02:3…           ┆ 19:03:25]            ┆                     │
│ 101  ┆ [97.0, 79.0, … 87.0]  ┆ [15:23:56, 17:05:14, ┆ [23:26:53, 01:08:12, ┆ [-65, -65, … 241]   │
│      ┆                       ┆ … 09:12:1…           ┆ … 17:03:2…           ┆                     │
│ 105  ┆ [125.0, 125.0, …      ┆ [18:59:55, 19:00:18, ┆ [01:49:15, 01:49:38, ┆ [51, 51, … 322]     │
│      ┆ 124.0]                ┆ … 09:31:3…           ┆ … 16:09:4…           ┆                     │
│ 109  ┆ [224.0, 160.0, …      ┆ [19:15:48, 19:18:07, ┆ [02:15:48, 02:18:07, ┆ [0, 0, … 258]       │
│      ┆ 107.0]                ┆ … 08:48:2…           ┆ … 16:50:4…           ┆                     │
│ 240  ┆ [211.0, 55.0, …       ┆ [22:08:23, 18:05:02, ┆ [05:08:23, 01:05:02, ┆ [-81, -80, … 329]   │
│      ┆ 175.0]                ┆ … 14:39:4…           ┆ … 20:37:1…           ┆                     │
│ …    ┆ …                     ┆ …                    ┆ …                    ┆ …                   │
│ 175  ┆ [160.0, 159.0, …      ┆ [16:36:11, 16:38:18, ┆ [23:35:34, 23:37:41, ┆ [0, 0, … 250]       │
│      ┆ 134.0]                ┆ … 12:23:5…           ┆ … 18:17:5…           ┆                     │
│ 69   ┆ [96.0, 110.0, …       ┆ [13:34:49, 13:35:02, ┆ [20:35:12, 20:35:25, ┆ [0, 0, … 205]       │
│      ┆ 186.0]                ┆ … 09:25:0…           ┆ … 16:23:4…           ┆                     │
│ 224  ┆ [149.0, 150.0, …      ┆ [17:55:45, 17:56:20, ┆ [00:55:45, 00:56:21, ┆ [0, 0, … 247]       │
│      ┆ 162.0]                ┆ … 10:58:2…           ┆ … 16:52:4…           ┆                     │
│ 257  ┆ [192.0, 98.0, …       ┆ [08:00:12, 08:08:54, ┆ [14:48:58, 14:57:40, ┆ [-60, -59, … 189]   │
│      ┆ 138.0]                ┆ … 08:51:3…           ┆ … 14:45:1…           ┆                     │
│ 43   ┆ [167.0, 167.0, …      ┆ [16:11:39, 16:16:36, ┆ [23:11:40, 23:16:36, ┆ [-33, -33, … 190]   │
│      ┆ 112.0]                ┆ … 10:26:2…           ┆ … 16:20:0…           ┆                     │
└──────┴───────────────────────┴──────────────────────┴──────────────────────┴─────────────────────┘

Obtain patient-level metadata.

All together...

In [6]:
meta = aleppo_dataset.load_metadata()
meta.head()

shape: (5, 125)
┌───────┬──────┬──────────┬────────┬───┬────────┬────────┬───────────┬───────┐
│ RecID ┆ PtID ┆ SiteOrig ┆ SiteID ┆ … ┆ Height ┆ Weight ┆ BMI       ┆ HbA1c │
│ ---   ┆ ---  ┆ ---      ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---       ┆ ---   │
│ i64   ┆ i32  ┆ i32      ┆ i32    ┆   ┆ f32    ┆ f32    ┆ f32       ┆ f64   │
╞═══════╪══════╪══════════╪════════╪═══╪════════╪════════╪═══════════╪═══════╡
│ 31431 ┆ 263  ┆ 15       ┆ 15     ┆ … ┆ 178.0  ┆ 106.0  ┆ 33.455376 ┆ 7.0   │
│ 31442 ┆ 101  ┆ 15       ┆ 15     ┆ … ┆ 183.0  ┆ 75.0   ┆ 22.395416 ┆ 5.85  │
│ 31476 ┆ 105  ┆ 15       ┆ 15     ┆ … ┆ 162.5  ┆ 62.0   ┆ 23.47929  ┆ 7.925 │
│ 31502 ┆ 109  ┆ 15       ┆ 15     ┆ … ┆ 163.0  ┆ 57.0   ┆ 21.453575 ┆ 7.175 │
│ 31512 ┆ 240  ┆ 15       ┆ 15     ┆ … ┆ 165.0  ┆ 63.0   ┆ 23.140497 ┆ 7.175 │
└───────┴──────┴──────────┴────────┴───┴────────┴────────┴───────────┴───────┘

In [7]:
cgm_subject = aleppo_dataset.get_subject_data(263)
cgm_subject

... or separately.

In [8]:
screening = aleppo_dataset.load_screening()
screening.head()

shape: (5, 43)
┌───────┬──────┬────────┬─────────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ RecID ┆ PtID ┆ SiteID ┆ EligCritMet ┆ … ┆ CGMUseDurati ┆ CGMUseDevic ┆ CGMDLoadMin ┆ CGMGlucUnde │
│ ---   ┆ ---  ┆ ---    ┆ ---         ┆   ┆ on           ┆ e           ┆ Days        ┆ r60         │
│ i64   ┆ i32  ┆ i64    ┆ str         ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│       ┆      ┆        ┆             ┆   ┆ str          ┆ str         ┆ str         ┆ str         │
╞═══════╪══════╪════════╪═════════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1     ┆ 40   ┆ 13     ┆ 1           ┆ … ┆ < 6 months   ┆ Dexcom      ┆ Yes         ┆ Yes         │
│ 4     ┆ 46   ┆ 5      ┆ 1           ┆ … ┆ 2 - < 5      ┆ Medtronic   ┆ Yes         ┆ Yes         │
│       ┆      ┆        ┆             ┆   ┆ years        ┆             ┆             ┆             │
│ 5     ┆ 109  ┆ 15     ┆ 1           ┆ … ┆ null         ┆ null        ┆ null        ┆ null        │
│ 7     ┆ 70   ┆ 5      ┆ 1           ┆ … ┆ null         ┆ null        ┆ null        ┆ null        │
│ 8     ┆ 101  ┆ 15     ┆ 1           ┆ … ┆ 2 - < 5      ┆ Dexcom      ┆ Yes         ┆ Yes         │
│       ┆      ┆        ┆             ┆   ┆ years        ┆             ┆             ┆             │
└───────┴──────┴────────┴─────────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [9]:
med_cond = aleppo_dataset.load_medical_condition()
med_cond.head()

shape: (5, 17)
┌───────┬──────┬────────┬──────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ RecID ┆ PtId ┆ SiteId ┆ MedCond      ┆ … ┆ MedCondStat ┆ MedCondDiag ┆ MedCondDiag ┆ MedCondCurr │
│ ---   ┆ ---  ┆ ---    ┆ ---          ┆   ┆ us          ┆ MonthsAfter ┆ YearsAfterE ┆ TreatMed    │
│ i64   ┆ i32  ┆ i32    ┆ str          ┆   ┆ ---         ┆ Enroll      ┆ nroll       ┆ ---         │
│       ┆      ┆        ┆              ┆   ┆ str         ┆ ---         ┆ ---         ┆ str         │
│       ┆      ┆        ┆              ┆   ┆             ┆ i32         ┆ i32         ┆             │
╞═══════╪══════╪════════╪══════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 1     ┆ 40   ┆ 13     ┆ Type I       ┆ … ┆ Ongoing     ┆ null        ┆ null        ┆ null        │
│       ┆      ┆        ┆ diabetes     ┆   ┆ (further    ┆             ┆             ┆             │
│       ┆      ┆        ┆ mellitus     ┆   ┆ improvement ┆             ┆             ┆             │
│       ┆      ┆        ┆              ┆   ┆ /…          ┆             ┆             ┆             │
│ 2     ┆ 40   ┆ 13     ┆ Dyslipidemia ┆ … ┆ Ongoing     ┆ null        ┆ null        ┆ null        │
│       ┆      ┆        ┆              ┆   ┆ (further    ┆             ┆             ┆             │
│       ┆      ┆        ┆              ┆   ┆ improvement ┆             ┆             ┆             │
│       ┆      ┆        ┆              ┆   ┆ /…          ┆             ┆             ┆             │
│ 8     ┆ 46   ┆ 5      ┆ Type I       ┆ … ┆ Ongoing,    ┆ null        ┆ null        ┆ null        │
│       ┆      ┆        ┆ diabetes     ┆   ┆ medically   ┆             ┆             ┆             │
│       ┆      ┆        ┆ mellitus     ┆   ┆ stable      ┆             ┆             ┆             │
│ 10    ┆ 263  ┆ 15     ┆ LDL          ┆ … ┆ Ongoing     ┆ null        ┆ null        ┆ null        │
│       ┆      ┆        ┆ cholesterol  ┆   ┆ (further    ┆             ┆             ┆             │
│       ┆      ┆        ┆ increased    ┆   ┆ improvement ┆             ┆             ┆             │
│       ┆      ┆        ┆              ┆   ┆ /…          ┆             ┆             ┆             │
│ 11    ┆ 70   ┆ 5      ┆ Type I       ┆ … ┆ Ongoing,    ┆ null        ┆ null        ┆ null        │
│       ┆      ┆        ┆ diabetes     ┆   ┆ medically   ┆             ┆             ┆             │
│       ┆      ┆        ┆ mellitus     ┆   ┆ stable      ┆             ┆             ┆             │
└───────┴──────┴────────┴──────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [10]:
medication = aleppo_dataset.load_medication()
medication.head()

shape: (5, 36)
┌───────┬──────┬────────┬──────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ RecID ┆ PtID ┆ SiteID ┆ DrugName     ┆ … ┆ MedStartDtU ┆ MedCondNotR ┆ PreExistCon ┆ AdvEventNot │
│ ---   ┆ ---  ┆ ---    ┆ ---          ┆   ┆ nk          ┆ eqd         ┆ dNotReqd    ┆ Reqd        │
│ i32   ┆ i32  ┆ i32    ┆ str          ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│       ┆      ┆        ┆              ┆   ┆ i32         ┆ i32         ┆ i32         ┆ i32         │
╞═══════╪══════╪════════╪══════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 1     ┆ 40   ┆ 13     ┆ Ramipril     ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ 12    ┆ 293  ┆ 10     ┆ Fexofenadine ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│       ┆      ┆        ┆ hydrochlorid ┆   ┆             ┆             ┆             ┆             │
│       ┆      ┆        ┆ e            ┆   ┆             ┆             ┆             ┆             │
│ 15    ┆ 137  ┆ 14     ┆ Ascorbic     ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│       ┆      ┆        ┆ Acid         ┆   ┆             ┆             ┆             ┆             │
│ 17    ┆ 137  ┆ 14     ┆ Vitamin D    ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
│ 18    ┆ 137  ┆ 14     ┆ Ibuprofen    ┆ … ┆ null        ┆ null        ┆ null        ┆ null        │
└───────┴──────┴────────┴──────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [11]:
roster = aleppo_dataset.load_roster()
roster.head()

shape: (5, 8)
┌───────┬──────┬──────────┬────────┬──────────────────────┬───────────┬──────────┬─────────────────┐
│ RecID ┆ PtID ┆ SiteOrig ┆ SiteID ┆ RandDtDaysAfterEnrol ┆ PtStatus  ┆ TrtGroup ┆ AgeAsOfEnrollDt │
│ ---   ┆ ---  ┆ ---      ┆ ---    ┆ l                    ┆ ---       ┆ ---      ┆ ---             │
│ i64   ┆ i32  ┆ i32      ┆ i32    ┆ ---                  ┆ str       ┆ str      ┆ i32             │
│       ┆      ┆          ┆        ┆ i32                  ┆           ┆          ┆                 │
╞═══════╪══════╪══════════╪════════╪══════════════════════╪═══════════╪══════════╪═════════════════╡
│ 31431 ┆ 263  ┆ 15       ┆ 15     ┆ 81                   ┆ Completed ┆ CGM Only ┆ 44              │
│ 31442 ┆ 101  ┆ 15       ┆ 15     ┆ 61                   ┆ Completed ┆ CGM+BGM  ┆ 27              │
│ 31476 ┆ 105  ┆ 15       ┆ 15     ┆ 142                  ┆ Completed ┆ CGM Only ┆ 42              │
│ 31502 ┆ 109  ┆ 15       ┆ 15     ┆ 83                   ┆ Completed ┆ CGM Only ┆ 78              │
│ 31512 ┆ 240  ┆ 15       ┆ 15     ┆ 144                  ┆ Completed ┆ CGM+BGM  ┆ 68              │
└───────┴──────┴──────────┴────────┴──────────────────────┴───────────┴──────────┴─────────────────┘

In [12]:
insulin = aleppo_dataset.load_insulin()
insulin.head()

shape: (5, 13)
┌───────┬──────┬────────┬──────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ RecID ┆ PtID ┆ SiteID ┆ InsName  ┆ … ┆ InsTypeStopD ┆ InsTypeStopU ┆ InsTypeStart ┆ InsTypeStopE │
│ ---   ┆ ---  ┆ ---    ┆ ---      ┆   ┆ tDaysFromEnr ┆ nknown       ┆ Estimate     ┆ stimate      │
│ i64   ┆ i32  ┆ i32    ┆ str      ┆   ┆ oll          ┆ ---          ┆ ---          ┆ ---          │
│       ┆      ┆        ┆          ┆   ┆ ---          ┆ str          ┆ str          ┆ str          │
│       ┆      ┆        ┆          ┆   ┆ i32          ┆              ┆              ┆              │
╞═══════╪══════╪════════╪══════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1     ┆ 40   ┆ 13     ┆ Novolog  ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│       ┆      ┆        ┆ (Aspart) ┆   ┆              ┆              ┆              ┆              │
│ 6     ┆ 70   ┆ 5      ┆ Humalog  ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│       ┆      ┆        ┆ (Lispro) ┆   ┆              ┆              ┆              ┆              │
│ 7     ┆ 293  ┆ 10     ┆ Novolog  ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│       ┆      ┆        ┆ (Aspart) ┆   ┆              ┆              ┆              ┆              │
│ 8     ┆ 137  ┆ 14     ┆ Novolog  ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│       ┆      ┆        ┆ (Aspart) ┆   ┆              ┆              ┆              ┆              │
│ 11    ┆ 143  ┆ 5      ┆ Novolog  ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│       ┆      ┆        ┆ (Aspart) ┆   ┆              ┆              ┆              ┆              │
└───────┴──────┴────────┴──────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [13]:
hba1c = aleppo_dataset.load_hba1c()
hba1c.head()

shape: (5, 8)
┌───────┬──────┬────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ RecID ┆ PtID ┆ SiteID ┆ Visit        ┆ HbA1cTestDtD ┆ HbA1cTestMet ┆ HbA1cTestRes ┆ HbA1cNotDone │
│ ---   ┆ ---  ┆ ---    ┆ ---          ┆ aysAfterEnro ┆ hod          ┆ ---          ┆ ---          │
│ i64   ┆ i32  ┆ i32    ┆ str          ┆ ll           ┆ ---          ┆ f64          ┆ str          │
│       ┆      ┆        ┆              ┆ ---          ┆ str          ┆              ┆              │
│       ┆      ┆        ┆              ┆ i32          ┆              ┆              ┆              │
╞═══════╪══════╪════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 10    ┆ 263  ┆ 15     ┆ Screening    ┆ -3           ┆ Point of     ┆ 7.0          ┆ null         │
│       ┆      ┆        ┆ Visit        ┆              ┆ Care         ┆              ┆              │
│ 51    ┆ 263  ┆ 15     ┆ Randomizatio ┆ 81           ┆ Point of     ┆ 7.0          ┆ null         │
│       ┆      ┆        ┆ n            ┆              ┆ Care         ┆              ┆              │
│ 175   ┆ 263  ┆ 15     ┆ Week 13      ┆ 165          ┆ Point of     ┆ 6.7          ┆ null         │
│       ┆      ┆        ┆ Visit        ┆              ┆ Care         ┆              ┆              │
│ 480   ┆ 263  ┆ 15     ┆ Week 26      ┆ 270          ┆ Point of     ┆ 7.3          ┆ null         │
│       ┆      ┆        ┆ Visit        ┆              ┆ Care         ┆              ┆              │
│ 8     ┆ 101  ┆ 15     ┆ Screening    ┆ -19          ┆ Point of     ┆ 5.9          ┆ null         │
│       ┆      ┆        ┆ Visit        ┆              ┆ Care         ┆              ┆              │
└───────┴──────┴────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [14]:
hba1c.filter(pl.col("PtID")==101)

shape: (4, 8)
┌───────┬──────┬────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ RecID ┆ PtID ┆ SiteID ┆ Visit        ┆ HbA1cTestDtD ┆ HbA1cTestMet ┆ HbA1cTestRes ┆ HbA1cNotDone │
│ ---   ┆ ---  ┆ ---    ┆ ---          ┆ aysAfterEnro ┆ hod          ┆ ---          ┆ ---          │
│ i64   ┆ i32  ┆ i32    ┆ str          ┆ ll           ┆ ---          ┆ f64          ┆ str          │
│       ┆      ┆        ┆              ┆ ---          ┆ str          ┆              ┆              │
│       ┆      ┆        ┆              ┆ i32          ┆              ┆              ┆              │
╞═══════╪══════╪════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 8     ┆ 101  ┆ 15     ┆ Screening    ┆ -19          ┆ Point of     ┆ 5.9          ┆ null         │
│       ┆      ┆        ┆ Visit        ┆              ┆ Care         ┆              ┆              │
│ 34    ┆ 101  ┆ 15     ┆ Randomizatio ┆ 61           ┆ Point of     ┆ 5.7          ┆ null         │
│       ┆      ┆        ┆ n            ┆              ┆ Care         ┆              ┆              │
│ 147   ┆ 101  ┆ 15     ┆ Week 13      ┆ 152          ┆ Point of     ┆ 5.6          ┆ null         │
│       ┆      ┆        ┆ Visit        ┆              ┆ Care         ┆              ┆              │
│ 396   ┆ 101  ┆ 15     ┆ Week 26      ┆ 241          ┆ Point of     ┆ 6.2          ┆ null         │
│       ┆      ┆        ┆ Visit        ┆              ┆ Care         ┆              ┆              │
└───────┴──────┴────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [15]:
hba1c["Visit"].unique()

shape: (4,)
Series: 'Visit' [str]
[
	"Week 26 Visit"
	"Week 13 Visit"
	"Screening Visit"
	"Randomization"
]

In [16]:
visit_info = aleppo_dataset.load_visit_info()
device_uploads = aleppo_dataset.load_device_uploads()

In [17]:
cgm_data = aleppo_dataset.cgm_data
cgm_data

shape: (226, 5)
┌──────┬───────────────────────┬──────────────────────┬──────────────────────┬─────────────────────┐
│ PtID ┆ glucemia_series       ┆ time_series          ┆ time_series_internal ┆ days_from_enroll    │
│ ---  ┆ ---                   ┆ ---                  ┆ ---                  ┆ ---                 │
│ i32  ┆ list[f64]             ┆ list[time]           ┆ list[time]           ┆ list[i64]           │
╞══════╪═══════════════════════╪══════════════════════╪══════════════════════╪═════════════════════╡
│ 263  ┆ [89.0, 87.0, … 159.0] ┆ [03:11:00, 03:16:00, ┆ [null, null, …       ┆ [-138, -138, … 270] │
│      ┆                       ┆ … 11:02:3…           ┆ 19:03:25]            ┆                     │
│ 101  ┆ [97.0, 79.0, … 87.0]  ┆ [15:23:56, 17:05:14, ┆ [23:26:53, 01:08:12, ┆ [-65, -65, … 241]   │
│      ┆                       ┆ … 09:12:1…           ┆ … 17:03:2…           ┆                     │
│ 105  ┆ [125.0, 125.0, …      ┆ [18:59:55, 19:00:18, ┆ [01:49:15, 01:49:38, ┆ [51, 51, … 322]     │
│      ┆ 124.0]                ┆ … 09:31:3…           ┆ … 16:09:4…           ┆                     │
│ 109  ┆ [224.0, 160.0, …      ┆ [19:15:48, 19:18:07, ┆ [02:15:48, 02:18:07, ┆ [0, 0, … 258]       │
│      ┆ 107.0]                ┆ … 08:48:2…           ┆ … 16:50:4…           ┆                     │
│ 240  ┆ [211.0, 55.0, …       ┆ [22:08:23, 18:05:02, ┆ [05:08:23, 01:05:02, ┆ [-81, -80, … 329]   │
│      ┆ 175.0]                ┆ … 14:39:4…           ┆ … 20:37:1…           ┆                     │
│ …    ┆ …                     ┆ …                    ┆ …                    ┆ …                   │
│ 175  ┆ [160.0, 159.0, …      ┆ [16:36:11, 16:38:18, ┆ [23:35:34, 23:37:41, ┆ [0, 0, … 250]       │
│      ┆ 134.0]                ┆ … 12:23:5…           ┆ … 18:17:5…           ┆                     │
│ 69   ┆ [96.0, 110.0, …       ┆ [13:34:49, 13:35:02, ┆ [20:35:12, 20:35:25, ┆ [0, 0, … 205]       │
│      ┆ 186.0]                ┆ … 09:25:0…           ┆ … 16:23:4…           ┆                     │
│ 224  ┆ [149.0, 150.0, …      ┆ [17:55:45, 17:56:20, ┆ [00:55:45, 00:56:21, ┆ [0, 0, … 247]       │
│      ┆ 162.0]                ┆ … 10:58:2…           ┆ … 16:52:4…           ┆                     │
│ 257  ┆ [192.0, 98.0, …       ┆ [08:00:12, 08:08:54, ┆ [14:48:58, 14:57:40, ┆ [-60, -59, … 189]   │
│      ┆ 138.0]                ┆ … 08:51:3…           ┆ … 14:45:1…           ┆                     │
│ 43   ┆ [167.0, 167.0, …      ┆ [16:11:39, 16:16:36, ┆ [23:11:40, 23:16:36, ┆ [-33, -33, … 190]   │
│      ┆ 112.0]                ┆ … 10:26:2…           ┆ … 16:20:0…           ┆                     │
└──────┴───────────────────────┴──────────────────────┴──────────────────────┴─────────────────────┘

In [18]:
visit_info

shape: (3_072, 10)
┌───────────────┬───────┬──────┬────────┬───┬──────────┬───────────────┬───────────┬───────────────┐
│ ParentLoginVi ┆ RecID ┆ PtID ┆ SiteID ┆ … ┆ OutOfWin ┆ OutOfWinReaso ┆ VisitMiss ┆ VisitMissReas │
│ sitID         ┆ ---   ┆ ---  ┆ ---    ┆   ┆ ---      ┆ n             ┆ ---       ┆ on            │
│ ---           ┆ i64   ┆ i32  ┆ i32    ┆   ┆ str      ┆ ---           ┆ str       ┆ ---           │
│ i64           ┆       ┆      ┆        ┆   ┆          ┆ str           ┆           ┆ str           │
╞═══════════════╪═══════╪══════╪════════╪═══╪══════════╪═══════════════╪═══════════╪═══════════════╡
│ 82987         ┆ 1     ┆ 40   ┆ 13     ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ 83529         ┆ 4     ┆ 46   ┆ 5      ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ 83548         ┆ 5     ┆ 40   ┆ 13     ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ 83556         ┆ 6     ┆ 40   ┆ 13     ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ 83590         ┆ 7     ┆ 46   ┆ 5      ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ …             ┆ …     ┆ …    ┆ …      ┆ … ┆ …        ┆ …             ┆ …         ┆ …             │
│ 118433        ┆ 3343  ┆ 60   ┆ 5      ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ 119263        ┆ 3344  ┆ 175  ┆ 7      ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ 119267        ┆ 3345  ┆ 224  ┆ 7      ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ 119297        ┆ 3346  ┆ 81   ┆ 8      ┆ … ┆ null     ┆ null          ┆ null      ┆ null          │
│ 119501        ┆ 3347  ┆ 265  ┆ 8      ┆ … ┆ 1        ┆ Work issue    ┆ null      ┆ null          │
└───────────────┴───────┴──────┴────────┴───┴──────────┴───────────────┴───────────┴───────────────┘

## Colas (2019)

In [19]:
colas= datasets["colas"]
print("metadata shape:", colas.metadata.shape)
print("cgm_data shape:", colas.cgm_data.shape)
print("joined_data shape:", colas.joined_data.shape)

metadata shape: (207, 9)
cgm_data shape: (207, 3)
joined_data shape: (207, 10)

In [20]:
colas.cgm_data

shape: (207, 3)
┌─────┬─────────────────────────────────┬─────────────────────────┐
│ id  ┆ time_series                     ┆ CGM                     │
│ --- ┆ ---                             ┆ ---                     │
│ i64 ┆ list[time]                      ┆ list[f64]               │
╞═════╪═════════════════════════════════╪═════════════════════════╡
│ 1   ┆ [00:00:14, 00:05:14, … 23:54:1… ┆ [86.0, 81.0, … 110.0]   │
│ 2   ┆ [00:00:35, 00:05:35, … 23:55:3… ┆ [167.0, 163.0, … 133.0] │
│ 3   ┆ [00:02:53, 00:07:53, … 23:57:5… ┆ [90.0, 90.0, … 97.0]    │
│ 4   ┆ [00:01:42, 00:06:42, … 23:58:3… ┆ [93.0, 92.0, … 111.0]   │
│ 5   ┆ [00:01:39, 00:06:39, … 23:56:4… ┆ [107.0, 109.0, … 134.0] │
│ …   ┆ …                               ┆ …                       │
│ 204 ┆ [00:01:21, 00:06:21, … 23:57:4… ┆ [140.0, 140.0, … 137.0] │
│ 205 ┆ [00:00:06, 00:05:06, … 23:57:0… ┆ [159.0, 160.0, … 143.0] │
│ 206 ┆ [00:01:16, 00:06:16, … 23:56:1… ┆ [113.0, 111.0, … 100.0] │
│ 207 ┆ [00:02:38, 00:07:38, … 23:58:3… ┆ [97.0, 99.0, … 105.0]   │
│ 208 ┆ [00:03:50, 00:08:50, … 23:58:5… ┆ [98.0, 97.0, … 96.0]    │
└─────┴─────────────────────────────────┴─────────────────────────┘

In [21]:
colas.metadata

shape: (207, 9)
┌─────┬────────┬─────┬───────────┬───┬───────┬───────────┬───────┬──────────────────┐
│ id  ┆ gender ┆ Age ┆ BMI       ┆ … ┆ HbA1c ┆ follow.up ┆ T2DM  ┆ Type of Diabetes │
│ --- ┆ ---    ┆ --- ┆ ---       ┆   ┆ ---   ┆ ---       ┆ ---   ┆ ---              │
│ i64 ┆ i32    ┆ i32 ┆ f32       ┆   ┆ f64   ┆ i32       ┆ bool  ┆ str              │
╞═════╪════════╪═════╪═══════════╪═══╪═══════╪═══════════╪═══════╪══════════════════╡
│ 1   ┆ 1      ┆ 77  ┆ 25.4      ┆ … ┆ 6.3   ┆ 413       ┆ false ┆ Control          │
│ 2   ┆ 0      ┆ 42  ┆ 30.0      ┆ … ┆ 5.8   ┆ 1185      ┆ false ┆ Control          │
│ 3   ┆ 0      ┆ 61  ┆ 33.799999 ┆ … ┆ 5.5   ┆ 560       ┆ false ┆ Control          │
│ 4   ┆ 0      ┆ 67  ┆ 26.700001 ┆ … ┆ 6.0   ┆ 1183      ┆ false ┆ Control          │
│ 5   ┆ 1      ┆ 53  ┆ 25.799999 ┆ … ┆ 5.2   ┆ 918       ┆ false ┆ Control          │
│ …   ┆ …      ┆ …   ┆ …         ┆ … ┆ …     ┆ …         ┆ …     ┆ …                │
│ 204 ┆ 0      ┆ 34  ┆ 28.4      ┆ … ┆ 5.7   ┆ 1027      ┆ false ┆ Control          │
│ 205 ┆ 0      ┆ 73  ┆ 28.0      ┆ … ┆ 6.0   ┆ 894       ┆ false ┆ Control          │
│ 206 ┆ 0      ┆ 58  ┆ 38.0      ┆ … ┆ 5.8   ┆ 1410      ┆ false ┆ Control          │
│ 207 ┆ 1      ┆ 74  ┆ 31.0      ┆ … ┆ 5.8   ┆ 1323      ┆ false ┆ Control          │
│ 208 ┆ 1      ┆ 67  ┆ 26.6      ┆ … ┆ 5.6   ┆ 1168      ┆ false ┆ Control          │
└─────┴────────┴─────┴───────────┴───┴───────┴───────────┴───────┴──────────────────┘

In [22]:
# Note: this id is missing
import polars as pl
print(colas.metadata.filter(pl.col("id") == 79))

shape: (0, 9)
┌─────┬────────┬─────┬─────┬───┬───────┬───────────┬──────┬──────────────────┐
│ id  ┆ gender ┆ Age ┆ BMI ┆ … ┆ HbA1c ┆ follow.up ┆ T2DM ┆ Type of Diabetes │
│ --- ┆ ---    ┆ --- ┆ --- ┆   ┆ ---   ┆ ---       ┆ ---  ┆ ---              │
│ i64 ┆ i32    ┆ i32 ┆ f32 ┆   ┆ f64   ┆ i32       ┆ bool ┆ str              │
╞═════╪════════╪═════╪═════╪═══╪═══════╪═══════════╪══════╪══════════════════╡
└─────┴────────┴─────┴─────┴───┴───────┴───────────┴──────┴──────────────────┘

## Zhao (2023)

In [23]:
zhao = datasets["zhao"]

In [24]:
print("metadata:", zhao.metadata.shape, zhao.metadata.columns)
print("cgm_data:", zhao.cgm_data.shape, zhao.cgm_data.columns)
print("joined_data:", zhao.joined_data.shape, zhao.joined_data.columns)

metadata: (108, 33) ['Patient Number', 'Gender (Female=1, Male=2)', 'Age', 'Height (m)', 'Weight (kg)', 'BMI', 'Smoking History (pack year)', 'Alcohol Drinking History (drinker/non-drinker)', 'Type of Diabetes', 'Duration of diabetes (years)', 'Acute Diabetic Complications', 'Diabetic Macrovascular  Complications', 'Diabetic Microvascular Complications', 'Comorbidities', 'Hypoglycemic Agents', 'Other Agents', 'Fasting Plasma Glucose (mg/dl)', '2-hour Postprandial Plasma Glucose (mg/dl)', 'Fasting C-peptide (nmol/L)', '2-hour Postprandial C-peptide (nmol/L)', 'Fasting Insulin (pmol/L)', '2-hour Postprandial insulin (pmol/L)', 'HbA1c (mmol/mol)', 'Glycated Albumin (%)', 'Total Cholesterol (mmol/L)', 'Triglyceride (mmol/L)', 'High-Density Lipoprotein Cholesterol (mmol/L)', 'Low-Density Lipoprotein Cholesterol (mmol/L)', 'Creatinine (umol/L)', 'Estimated Glomerular Filtration Rate  (ml/min/1.73m2) ', 'Uric Acid (mmol/L)', 'Blood Urea Nitrogen (mmol/L)', 'Hypoglycemia (yes/no)']
cgm_data: (108, 12) ['Date', 'CGM', 'CBG', 'Blood Ketone', 'DI (Eng)', 'DI (Ch)', 'Insulin (s.c.)', 'NIHA', 'CSII Bolus', 'CSII Basal', 'Insulin (i.v.)', 'Patient Number']
joined_data: (108, 44) ['Patient Number', 'Gender (Female=1, Male=2)', 'Age', 'Height (m)', 'Weight (kg)', 'BMI', 'Smoking History (pack year)', 'Alcohol Drinking History (drinker/non-drinker)', 'Type of Diabetes', 'Duration of diabetes (years)', 'Acute Diabetic Complications', 'Diabetic Macrovascular  Complications', 'Diabetic Microvascular Complications', 'Comorbidities', 'Hypoglycemic Agents', 'Other Agents', 'Fasting Plasma Glucose (mg/dl)', '2-hour Postprandial Plasma Glucose (mg/dl)', 'Fasting C-peptide (nmol/L)', '2-hour Postprandial C-peptide (nmol/L)', 'Fasting Insulin (pmol/L)', '2-hour Postprandial insulin (pmol/L)', 'Glycated Albumin (%)', 'Total Cholesterol (mmol/L)', 'Triglyceride (mmol/L)', 'High-Density Lipoprotein Cholesterol (mmol/L)', 'Low-Density Lipoprotein Cholesterol (mmol/L)', 'Creatinine (umol/L)', 'Estimated Glomerular Filtration Rate  (ml/min/1.73m2) ', 'Uric Acid (mmol/L)', 'Blood Urea Nitrogen (mmol/L)', 'Hypoglycemia (yes/no)', 'time_series', 'CGM', 'CBG', 'Blood Ketone', 'DI (Eng)', 'DI (Ch)', 'Insulin (s.c.)', 'NIHA', 'CSII Bolus', 'CSII Basal', 'Insulin (i.v.)', 'HbA1c']

In [25]:
print(zhao.metadata.head())
print(zhao.cgm_data.head())
print(zhao.joined_data.head())

shape: (5, 33)
┌─────────────┬─────────────┬─────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Patient     ┆ Gender      ┆ Age ┆ Height ┆ … ┆ Estimated  ┆ Uric Acid  ┆ Blood Urea ┆ Hypoglycem │
│ Number      ┆ (Female=1,  ┆ --- ┆ (m)    ┆   ┆ Glomerular ┆ (mmol/L)   ┆ Nitrogen   ┆ ia         │
│ ---         ┆ Male=2)     ┆ i32 ┆ ---    ┆   ┆ Filtratio… ┆ ---        ┆ (mmol/L)   ┆ (yes/no)   │
│ str         ┆ ---         ┆     ┆ f64    ┆   ┆ ---        ┆ f64        ┆ ---        ┆ ---        │
│             ┆ i64         ┆     ┆        ┆   ┆ f64        ┆            ┆ f64        ┆ bool       │
╞═════════════╪═════════════╪═════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2000_0_2020 ┆ 2           ┆ 57  ┆ 1.69   ┆ … ┆ 68.0       ┆ 245.0      ┆ 4.9        ┆ true       │
│ 1230        ┆             ┆     ┆        ┆   ┆            ┆            ┆            ┆            │
│ 2001_0_2020 ┆ 1           ┆ 69  ┆ 1.45   ┆ … ┆ 101.0      ┆ 337.0      ┆ 5.6        ┆ true       │
│ 1102        ┆             ┆     ┆        ┆   ┆            ┆            ┆            ┆            │
│ 2001_1_2020 ┆ 1           ┆ 69  ┆ 1.45   ┆ … ┆ 103.0      ┆ 262.0      ┆ 3.7        ┆ false      │
│ 1117        ┆             ┆     ┆        ┆   ┆            ┆            ┆            ┆            │
│ 2002_0_2021 ┆ 2           ┆ 57  ┆ 1.7    ┆ … ┆ 105.0      ┆ 475.6      ┆ 4.74       ┆ false      │
│ 0513        ┆             ┆     ┆        ┆   ┆            ┆            ┆            ┆            │
│ 2003_0_2021 ┆ 1           ┆ 58  ┆ 1.64   ┆ … ┆ 166.0      ┆ 490.05     ┆ 5.54       ┆ false      │
│ 0615        ┆             ┆     ┆        ┆   ┆            ┆            ┆            ┆            │
└─────────────┴─────────────┴─────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘
shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ CGM       ┆ CBG       ┆ Blood     ┆ … ┆ CSII      ┆ CSII      ┆ Insulin   ┆ Patient  │
│ ---       ┆ ---       ┆ ---       ┆ Ketone    ┆   ┆ Bolus     ┆ Basal     ┆ (i.v.)    ┆ Number   │
│ list[date ┆ list[f64] ┆ list[f64] ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ time[μs]] ┆           ┆           ┆ list[f64] ┆   ┆ list[f64] ┆ list[f64] ┆ list[str] ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [2020-12- ┆ [138.6,   ┆ [null,    ┆ [null,    ┆ … ┆ [null,    ┆ [null,    ┆ [null,    ┆ 2000_0_2 │
│ 30        ┆ 120.6, …  ┆ null, …   ┆ null, …   ┆   ┆ null, …   ┆ null, …   ┆ null, …   ┆ 0201230  │
│ 13:54:00, ┆ 88.2]     ┆ null]     ┆ null]     ┆   ┆ null]     ┆ null]     ┆ null]     ┆          │
│ 2020-12-… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [2020-11- ┆ [102.6,   ┆ [null,    ┆ [null,    ┆ … ┆ [null,    ┆ [null,    ┆ [null,    ┆ 2001_0_2 │
│ 02        ┆ 97.2, …   ┆ 104.4, …  ┆ null, …   ┆   ┆ null, …   ┆ null, …   ┆ null, …   ┆ 0201102  │
│ 09:40:00, ┆ 136.8]    ┆ null]     ┆ null]     ┆   ┆ null]     ┆ null]     ┆ null]     ┆          │
│ 2020-11-… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [2020-11- ┆ [151.2,   ┆ [null,    ┆ [null,    ┆ … ┆ [null,    ┆ [null,    ┆ [null,    ┆ 2001_1_2 │
│ 17        ┆ 145.8, …  ┆ null, …   ┆ null, …   ┆   ┆ null, …   ┆ null, …   ┆ null, …   ┆ 0201117  │
│ 09:19:00, ┆ 180.0]    ┆ null]     ┆ null]     ┆   ┆ null]     ┆ null]     ┆ null]     ┆          │
│ 2020-11-… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [2021-05- ┆ [257.4,   ┆ [null,    ┆ [null,    ┆ … ┆ [null,    ┆ [0.6,     ┆ [null,    ┆ 2002_0_2 │
│ 13        ┆ 246.6, …  ┆ null, …   ┆ null, …   ┆   ┆ null, …   ┆ null, …   ┆ null, …   ┆ 0210513  │
│ 16:22:00, ┆ 217.8]    ┆ null]     ┆ null]     ┆   ┆ null]     ┆ null]     ┆ null]     ┆          │
│ 2021-05-… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ [2021-06- ┆ [264.6,   ┆ [null,    ┆ [null,    ┆ … ┆ [null,    ┆ [0.5,     ┆ [null,    ┆ 2003_0_2 │
│ 15        ┆ 262.8, …  ┆ null, …   ┆ null, …   ┆   ┆ null, …   ┆ null, …   ┆ null, …   ┆ 0210615  │
│ 17:20:00, ┆ 180.0]    ┆ null]     ┆ null]     ┆   ┆ null]     ┆ null]     ┆ null]     ┆          │
│ 2021-06-… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘
shape: (5, 44)
┌─────────────┬─────────────┬─────┬────────┬───┬─────────────┬────────────┬────────────┬───────────┐
│ Patient     ┆ Gender      ┆ Age ┆ Height ┆ … ┆ CSII Bolus  ┆ CSII Basal ┆ Insulin    ┆ HbA1c     │
│ Number      ┆ (Female=1,  ┆ --- ┆ (m)    ┆   ┆ ---         ┆ ---        ┆ (i.v.)     ┆ ---       │
│ ---         ┆ Male=2)     ┆ i32 ┆ ---    ┆   ┆ list[f64]   ┆ list[f64]  ┆ ---        ┆ f64       │
│ str         ┆ ---         ┆     ┆ f64    ┆   ┆             ┆            ┆ list[str]  ┆           │
│             ┆ i64         ┆     ┆        ┆   ┆             ┆            ┆            ┆           │
╞═════════════╪═════════════╪═════╪════════╪═══╪═════════════╪════════════╪════════════╪═══════════╡
│ 2000_0_2020 ┆ 2           ┆ 57  ┆ 1.69   ┆ … ┆ [null,      ┆ [null,     ┆ [null,     ┆ 7.601281  │
│ 1230        ┆             ┆     ┆        ┆   ┆ null, …     ┆ null, …    ┆ null, …    ┆           │
│             ┆             ┆     ┆        ┆   ┆ null]       ┆ null]      ┆ null]      ┆           │
│ 2001_0_2020 ┆ 1           ┆ 69  ┆ 1.45   ┆ … ┆ [null,      ┆ [null,     ┆ [null,     ┆ 7.401305  │
│ 1102        ┆             ┆     ┆        ┆   ┆ null, …     ┆ null, …    ┆ null, …    ┆           │
│             ┆             ┆     ┆        ┆   ┆ null]       ┆ null]      ┆ null]      ┆           │
│ 2001_1_2020 ┆ 1           ┆ 69  ┆ 1.45   ┆ … ┆ [null,      ┆ [null,     ┆ [null,     ┆ 7.301318  │
│ 1117        ┆             ┆     ┆        ┆   ┆ null, …     ┆ null, …    ┆ null, …    ┆           │
│             ┆             ┆     ┆        ┆   ┆ null]       ┆ null]      ┆ null]      ┆           │
│ 2002_0_2021 ┆ 2           ┆ 57  ┆ 1.7    ┆ … ┆ [null,      ┆ [0.6,      ┆ [null,     ┆ 9.201083  │
│ 0513        ┆             ┆     ┆        ┆   ┆ null, …     ┆ null, …    ┆ null, …    ┆           │
│             ┆             ┆     ┆        ┆   ┆ null]       ┆ null]      ┆ null]      ┆           │
│ 2003_0_2021 ┆ 1           ┆ 58  ┆ 1.64   ┆ … ┆ [null,      ┆ [0.5,      ┆ [null,     ┆ 9.5010458 │
│ 0615        ┆             ┆     ┆        ┆   ┆ null, …     ┆ null, …    ┆ null, …    ┆           │
│             ┆             ┆     ┆        ┆   ┆ null]       ┆ null]      ┆ null]      ┆           │
└─────────────┴─────────────┴─────┴────────┴───┴─────────────┴────────────┴────────────┴───────────┘

In [26]:
# Rebuild Methods (for understanding internals)
cgm_rebuilt = zhao.construct_cgm_dataframe()
joined_rebuilt = zhao.construct_joined_dataframe()
print("rebuilt cgm_data shape:", cgm_rebuilt.shape)
print("rebuilt joined_data shape:", joined_rebuilt.shape)

rebuilt cgm_data shape: (108, 12)
rebuilt joined_data shape: (108, 44)

Subject-Level Access

Use `ids` + `get_subject_data` to inspect one subject in detail.

In [27]:
sid = zhao.ids[0]
subj = zhao.get_subject_data(sid)
print(subj.metadata)

shape: (1, 33)
┌─────────────┬─────────────┬─────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Patient     ┆ Gender      ┆ Age ┆ Height ┆ … ┆ Estimated  ┆ Uric Acid  ┆ Blood Urea ┆ Hypoglycem │
│ Number      ┆ (Female=1,  ┆ --- ┆ (m)    ┆   ┆ Glomerular ┆ (mmol/L)   ┆ Nitrogen   ┆ ia         │
│ ---         ┆ Male=2)     ┆ i32 ┆ ---    ┆   ┆ Filtratio… ┆ ---        ┆ (mmol/L)   ┆ (yes/no)   │
│ str         ┆ ---         ┆     ┆ f64    ┆   ┆ ---        ┆ f64        ┆ ---        ┆ ---        │
│             ┆ i64         ┆     ┆        ┆   ┆ f64        ┆            ┆ f64        ┆ bool       │
╞═════════════╪═════════════╪═════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2000_0_2020 ┆ 2           ┆ 57  ┆ 1.69   ┆ … ┆ 68.0       ┆ 245.0      ┆ 4.9        ┆ true       │
│ 1230        ┆             ┆     ┆        ┆   ┆            ┆            ┆            ┆            │
└─────────────┴─────────────┴─────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [28]:
print("Subject CGM rows:", subj.cgm_readings.height)
subj.cgm_readings.head()

Subject CGM rows: 1339

shape: (5, 11)
┌─────────────────────┬───────┬──────┬──────────────┬───┬──────┬────────────┬────────────┬─────────┐
│ Date                ┆ CGM   ┆ CBG  ┆ Blood Ketone ┆ … ┆ NIHA ┆ CSII Bolus ┆ CSII Basal ┆ Insulin │
│ ---                 ┆ ---   ┆ ---  ┆ ---          ┆   ┆ ---  ┆ ---        ┆ ---        ┆ (i.v.)  │
│ datetime[μs]        ┆ f64   ┆ f64  ┆ f64          ┆   ┆ str  ┆ f64        ┆ f64        ┆ ---     │
│                     ┆       ┆      ┆              ┆   ┆      ┆            ┆            ┆ str     │
╞═════════════════════╪═══════╪══════╪══════════════╪═══╪══════╪════════════╪════════════╪═════════╡
│ 2020-12-30 13:54:00 ┆ 138.6 ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
│ 2020-12-30 14:09:00 ┆ 120.6 ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
│ 2020-12-30 14:24:00 ┆ 106.2 ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
│ 2020-12-30 14:39:00 ┆ 97.2  ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
│ 2020-12-30 14:54:00 ┆ 88.2  ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
└─────────────────────┴───────┴──────┴──────────────┴───┴──────┴────────────┴────────────┴─────────┘

In [29]:
subj.cgm_readings.select(
    pl.len().alias("n_rows"),
    pl.col("Date").min().alias("start"),
    pl.col("Date").max().alias("end"),
    pl.col("CGM").mean().alias("mean_cgm"),
    pl.col("CGM").min().alias("min_cgm"),
    pl.col("CGM").max().alias("max_cgm"),
)

shape: (1, 6)
┌────────┬─────────────────────┬─────────────────────┬───────────┬─────────┬─────────┐
│ n_rows ┆ start               ┆ end                 ┆ mean_cgm  ┆ min_cgm ┆ max_cgm │
│ ---    ┆ ---                 ┆ ---                 ┆ ---       ┆ ---     ┆ ---     │
│ u32    ┆ datetime[μs]        ┆ datetime[μs]        ┆ f64       ┆ f64     ┆ f64     │
╞════════╪═════════════════════╪═════════════════════╪═══════════╪═════════╪═════════╡
│ 1339   ┆ 2020-12-30 13:54:00 ┆ 2021-01-13 12:24:00 ┆ 118.95997 ┆ 39.6    ┆ 252.0   │
└────────┴─────────────────────┴─────────────────────┴───────────┴─────────┴─────────┘

CGM Representation Round-Trip

`cgm_to_single_row()` converts a subject to list-columns; `single_row_to_cgm()` restores long format.

In [30]:
single = subj.cgm_to_single_row()
roundtrip = subj.single_row_to_cgm(single)
print("single-row shape:", single.shape)
print("roundtrip shape:", roundtrip.shape)
roundtrip.head()

single-row shape: (1, 12)
roundtrip shape: (1339, 11)

shape: (5, 11)
┌─────────────────────┬───────┬──────┬──────────────┬───┬──────┬────────────┬────────────┬─────────┐
│ Date                ┆ CGM   ┆ CBG  ┆ Blood Ketone ┆ … ┆ NIHA ┆ CSII Bolus ┆ CSII Basal ┆ Insulin │
│ ---                 ┆ ---   ┆ ---  ┆ ---          ┆   ┆ ---  ┆ ---        ┆ ---        ┆ (i.v.)  │
│ datetime[μs]        ┆ f64   ┆ f64  ┆ f64          ┆   ┆ str  ┆ f64        ┆ f64        ┆ ---     │
│                     ┆       ┆      ┆              ┆   ┆      ┆            ┆            ┆ str     │
╞═════════════════════╪═══════╪══════╪══════════════╪═══╪══════╪════════════╪════════════╪═════════╡
│ 2020-12-30 13:54:00 ┆ 138.6 ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
│ 2020-12-30 14:09:00 ┆ 120.6 ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
│ 2020-12-30 14:24:00 ┆ 106.2 ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
│ 2020-12-30 14:39:00 ┆ 97.2  ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
│ 2020-12-30 14:54:00 ┆ 88.2  ┆ null ┆ null         ┆ … ┆ null ┆ null       ┆ null       ┆ null    │
└─────────────────────┴───────┴──────┴──────────────┴───┴──────┴────────────┴────────────┴─────────┘

## Praesiidium

In [31]:
datasets, errors = load_datasets(
    config_path="datasets.toml",
    only=["praes_unil"], # if loading praes_mug, expect validation errors
)
if errors:
    raise RuntimeError(errors)

praes = datasets["praes_unil"]

➡️ Loading datasets.praes_unil

In [32]:
praes.cgm_data.head()

shape: (5, 3)
┌───────────────┬─────────────────────────────────┬───────────────────┐
│ participantId ┆ time_series                     ┆ CGM               │
│ ---           ┆ ---                             ┆ ---               │
│ str           ┆ list[datetime[μs]]              ┆ list[f64]         │
╞═══════════════╪═════════════════════════════════╪═══════════════════╡
│ s24529531     ┆ [2024-06-05 10:25:00, 2024-06-… ┆ [5.3, 5.6, … 5.3] │
│ s24516746     ┆ [2024-05-21 14:16:00, 2024-05-… ┆ [4.2, 4.0, … 6.1] │
│ s243281021    ┆ [2024-04-05 10:29:00, 2024-04-… ┆ [5.6, 5.5, … 4.7] │
│ s245161136    ┆ [2024-05-23 12:27:00, 2024-05-… ┆ [5.4, 5.5, … 5.0] │
│ s24417854     ┆ [2024-04-24 12:47:00, 2024-04-… ┆ [4.9, 4.9, … 4.8] │
└───────────────┴─────────────────────────────────┴───────────────────┘

In [33]:
praes.metadata.head()

shape: (5, 24)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ participa ┆ nickname ┆ email     ┆ emailVeri ┆ … ┆ LiquorsPe ┆ missingDa ┆ DoctorNot ┆ BMI       │
│ ntId      ┆ ---      ┆ ---       ┆ fication  ┆   ┆ rWeek     ┆ ta        ┆ es        ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│ str       ┆          ┆           ┆ str       ┆   ┆ f64       ┆ bool      ┆ str       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ s24529531 ┆ LP032    ┆ lp032lv20 ┆ lp032lv20 ┆ … ┆ 0.0       ┆ false     ┆ null      ┆ 28.136244 │
│           ┆          ┆ 24l@gmail ┆ 24l@gmail ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ .com      ┆ .com      ┆   ┆           ┆           ┆           ┆           │
│ s24516746 ┆ LP023    ┆ lp023lv20 ┆ lp023lv20 ┆ … ┆ 0.0       ┆ false     ┆ null      ┆ 27.187853 │
│           ┆          ┆ 24@gmail. ┆ 24@gmail. ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ com       ┆ com       ┆   ┆           ┆           ┆           ┆           │
│ s24328102 ┆ LP003    ┆ lp003lv20 ┆ lp003lv20 ┆ … ┆ 0.0       ┆ false     ┆ null      ┆ 29.998979 │
│ 1         ┆          ┆ 24@gmail. ┆ 24@gmail. ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ com       ┆ com       ┆   ┆           ┆           ┆           ┆           │
│ s24516113 ┆ LP025    ┆ lp025lv20 ┆ lp025lv20 ┆ … ┆ 0.0       ┆ false     ┆ null      ┆ 26.171875 │
│ 6         ┆          ┆ 24@gmail. ┆ 24@gmail. ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ com       ┆ com       ┆   ┆           ┆           ┆           ┆           │
│ s24417854 ┆ LP007    ┆ lp007lv20 ┆ lp007lv20 ┆ … ┆ 0.0       ┆ false     ┆ null      ┆ 31.377989 │
│           ┆          ┆ 24@gmail. ┆ 24@gmail. ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ com       ┆ com       ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Inspecting the dataset

In [34]:
ds = praes.dataset

In [35]:
subjects = ds.subjects
print(len(subjects))

77

Accessing the clinical data (biomarkers measurements and visits data).

In [36]:
analyses = ds.get_aggregated_analysis_frame()
analyses.head()

shape: (5, 38)
┌──────────────┬───────┬─────────────┬───────────┬───┬────────┬────────┬─────────────┬─────────────┐
│ formId       ┆ HbA1c ┆ Fasting_blo ┆ C_peptide ┆ … ┆ IL_10  ┆ Leptin ┆ missingData ┆ participant │
│ ---          ┆ ---   ┆ od_glucose  ┆ ---       ┆   ┆ ---    ┆ ---    ┆ ---         ┆ Id          │
│ str          ┆ f64   ┆ ---         ┆ f64       ┆   ┆ f64    ┆ f64    ┆ str         ┆ ---         │
│              ┆       ┆ f64         ┆           ┆   ┆        ┆        ┆             ┆ str         │
╞══════════════╪═══════╪═════════════╪═══════════╪═══╪════════╪════════╪═════════════╪═════════════╡
│ VISIT1_ANALY ┆ null  ┆ 5.41        ┆ 1.51      ┆ … ┆ 22.17  ┆ 1500.2 ┆ false       ┆ s24529531   │
│ SISRESULT_UN ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ IL           ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ VISIT2_ANALY ┆ 5.31  ┆ 5.4         ┆ null      ┆ … ┆ 15.97  ┆ 2068.9 ┆ false       ┆ s24529531   │
│ SISRESULT_UN ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ IL           ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ VISIT3_ANALY ┆ 5.35  ┆ 5.29        ┆ 1.85      ┆ … ┆ 25.5   ┆ 1836.7 ┆ false       ┆ s24529531   │
│ SISRESULT_UN ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ IL           ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ VISIT1_ANALY ┆ null  ┆ 4.85        ┆ 1.53      ┆ … ┆ 341.9  ┆ 6438.6 ┆ false       ┆ s24516746   │
│ SISRESULT_UN ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ IL           ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ VISIT2_ANALY ┆ 5.13  ┆ 4.95        ┆ null      ┆ … ┆ 332.79 ┆ 9493.0 ┆ false       ┆ s24516746   │
│ SISRESULT_UN ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
│ IL           ┆       ┆             ┆           ┆   ┆        ┆        ┆             ┆             │
└──────────────┴───────┴─────────────┴───────────┴───┴────────┴────────┴─────────────┴─────────────┘

In [37]:
visits = ds.get_aggregated_visit_frame()
visits.head()

shape: (5, 19)
┌──────┬───────────┬──────┬──────────┬───┬─────────────┬───────────────┬────────────┬─────────┐
│ Age  ┆ BloodTest ┆ CGM  ┆ Distance ┆ … ┆ missingData ┆ participantId ┆ recall_24h ┆ visitId │
│ ---  ┆ ---       ┆ ---  ┆ ---      ┆   ┆ ---         ┆ ---           ┆ ---        ┆ ---     │
│ f64  ┆ str       ┆ str  ┆ f64      ┆   ┆ bool        ┆ str           ┆ str        ┆ str     │
╞══════╪═══════════╪══════╪══════════╪═══╪═════════════╪═══════════════╪════════════╪═════════╡
│ 55.0 ┆ Yes       ┆ Yes  ┆ 658.0    ┆ … ┆ false       ┆ s24529531     ┆ Yes        ┆ visit1  │
│ 55.0 ┆ Yes       ┆ Yes  ┆ 647.0    ┆ … ┆ false       ┆ s24529531     ┆ Yes        ┆ visit2  │
│ 55.0 ┆ Yes       ┆ null ┆ 627.0    ┆ … ┆ false       ┆ s24529531     ┆ Yes        ┆ visit3  │
│ 27.0 ┆ Yes       ┆ Yes  ┆ 658.0    ┆ … ┆ false       ┆ s24516746     ┆ Yes        ┆ visit1  │
│ 27.0 ┆ Yes       ┆ Yes  ┆ 633.0    ┆ … ┆ false       ┆ s24516746     ┆ Yes        ┆ visit2  │
└──────┴───────────┴──────┴──────────┴───┴─────────────┴───────────────┴────────────┴─────────┘

In [38]:
visits_subject_grouped = ds.get_aggregated_visit_frame(group_by=True)
visits_subject_grouped.head()

shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ participa ┆ Age       ┆ BloodTest ┆ CGM       ┆ … ┆ Weight    ┆ missingDa ┆ recall_24 ┆ visitId  │
│ ntId      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ta        ┆ h         ┆ ---      │
│ ---       ┆ list[f64] ┆ list[str] ┆ list[str] ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ list[str │
│ str       ┆           ┆           ┆           ┆   ┆           ┆ list[bool ┆ list[str] ┆ ]        │
│           ┆           ┆           ┆           ┆   ┆           ┆ ]         ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s24516113 ┆ [29.0,    ┆ ["Yes",   ┆ ["Yes",   ┆ … ┆ [67.6,    ┆ [false,   ┆ ["Yes",   ┆ ["visit1 │
│ 6         ┆ 29.0,     ┆ "Yes",    ┆ "Yes",    ┆   ┆ 68.0,     ┆ false,    ┆ "Yes",    ┆ ", "visi │
│           ┆ 29.0]     ┆ "Yes"]    ┆ null]     ┆   ┆ 67.8]     ┆ false]    ┆ "Yes"]    ┆ t2", "vi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ sit3"]   │
│ s24528748 ┆ [36.0,    ┆ ["Yes",   ┆ ["Yes",   ┆ … ┆ [85.2,    ┆ [false,   ┆ ["Yes",   ┆ ["visit1 │
│           ┆ 36.0,     ┆ "Yes",    ┆ "Yes",    ┆   ┆ 85.4,     ┆ false,    ┆ "Yes",    ┆ ", "visi │
│           ┆ 36.0]     ┆ "Yes"]    ┆ null]     ┆   ┆ 85.4]     ┆ false]    ┆ "Yes"]    ┆ t2", "vi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ sit3"]   │
│ s2472952  ┆ [33.0,    ┆ ["Yes",   ┆ ["Yes",   ┆ … ┆ [78.4,    ┆ [false,   ┆ ["Yes",   ┆ ["visit1 │
│           ┆ 33.0,     ┆ "Yes",    ┆ "Yes",    ┆   ┆ 78.0,     ┆ false,    ┆ "No",     ┆ ", "visi │
│           ┆ 33.0]     ┆ "Yes"]    ┆ null]     ┆   ┆ 76.7]     ┆ false]    ┆ "Yes"]    ┆ t2", "vi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ sit3"]   │
│ s24328102 ┆ [40.0,    ┆ ["Yes",   ┆ ["Yes",   ┆ … ┆ [80.0,    ┆ [false,   ┆ ["Yes",   ┆ ["visit1 │
│ 1         ┆ 40.0,     ┆ "Yes",    ┆ "Yes",    ┆   ┆ 81.0,     ┆ false,    ┆ "Yes",    ┆ ", "visi │
│           ┆ 40.0]     ┆ "Yes"]    ┆ null]     ┆   ┆ 81.0]     ┆ false]    ┆ "Yes"]    ┆ t2", "vi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ sit3"]   │
│ s2457121  ┆ [35.0,    ┆ ["Yes",   ┆ ["Yes",   ┆ … ┆ [87.5,    ┆ [false,   ┆ ["Yes",   ┆ ["visit1 │
│           ┆ 35.0,     ┆ "Yes",    ┆ "Yes",    ┆   ┆ 87.5,     ┆ false,    ┆ "No",     ┆ ", "visi │
│           ┆ 35.0]     ┆ "Yes"]    ┆ null]     ┆   ┆ 85.4]     ┆ false]    ┆ "Yes"]    ┆ t2", "vi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ sit3"]   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Accessing the CGM data.

In [39]:
# CGM readings divided by visit ...
v2_cgm = ds.get_all_cgm_visit_frames("visit2")
v3_cgm = ds.get_all_cgm_visit_frames("visit3")
v2_cgm.head()

shape: (5, 7)
┌───────────────────┬──────────────────┬───────────────┬─────────┬────────────┬─────────────┬──────┐
│ deviceTimestamp   ┆ historicGlucoseM ┆ participantId ┆ visitId ┆ visitDate  ┆ date_notime ┆ hour │
│ ---               ┆ molL             ┆ ---           ┆ ---     ┆ ---        ┆ ---         ┆ ---  │
│ datetime[μs]      ┆ ---              ┆ str           ┆ str     ┆ date       ┆ date        ┆ i8   │
│                   ┆ f64              ┆               ┆         ┆            ┆             ┆      │
╞═══════════════════╪══════════════════╪═══════════════╪═════════╪════════════╪═════════════╪══════╡
│ 2024-06-05        ┆ 5.3              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 10   │
│ 10:25:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
│ 2024-06-05        ┆ 5.6              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 10   │
│ 10:40:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
│ 2024-06-05        ┆ 6.5              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 10   │
│ 10:55:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
│ 2024-06-05        ┆ 7.1              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 11   │
│ 11:10:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
│ 2024-06-05        ┆ 6.7              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 11   │
│ 11:25:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
└───────────────────┴──────────────────┴───────────────┴─────────┴────────────┴─────────────┴──────┘

In [40]:
# ... or their concatenation
cgms = ds.get_all_cgm_long_frame(visit_ids=["visit2", "visit3"])
cgms.head()

shape: (5, 7)
┌───────────────────┬──────────────────┬───────────────┬─────────┬────────────┬─────────────┬──────┐
│ deviceTimestamp   ┆ historicGlucoseM ┆ participantId ┆ visitId ┆ visitDate  ┆ date_notime ┆ hour │
│ ---               ┆ molL             ┆ ---           ┆ ---     ┆ ---        ┆ ---         ┆ ---  │
│ datetime[μs]      ┆ ---              ┆ str           ┆ str     ┆ date       ┆ date        ┆ i8   │
│                   ┆ f64              ┆               ┆         ┆            ┆             ┆      │
╞═══════════════════╪══════════════════╪═══════════════╪═════════╪════════════╪═════════════╪══════╡
│ 2024-06-05        ┆ 5.3              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 10   │
│ 10:25:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
│ 2024-06-05        ┆ 5.6              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 10   │
│ 10:40:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
│ 2024-06-05        ┆ 6.5              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 10   │
│ 10:55:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
│ 2024-06-05        ┆ 7.1              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 11   │
│ 11:10:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
│ 2024-06-05        ┆ 6.7              ┆ s24529531     ┆ visit2  ┆ 2024-07-31 ┆ 2024-06-05  ┆ 11   │
│ 11:25:00          ┆                  ┆               ┆         ┆            ┆             ┆      │
└───────────────────┴──────────────────┴───────────────┴─────────┴────────────┴─────────────┴──────┘

In [41]:
cgms_with_device = ds.get_aggregated_cgm_frame()
cgms_with_device.head()

shape: (5, 6)
┌─────────────────┬───────────────┬─────────────────┬────────────┬─────────────────┬───────────────┐
│ device          ┆ serialNumber  ┆ deviceTimestamp ┆ recordType ┆ historicGlucose ┆ participantId │
│ ---             ┆ ---           ┆ ---             ┆ ---        ┆ MmolL           ┆ ---           │
│ str             ┆ str           ┆ datetime[μs]    ┆ i64        ┆ ---             ┆ str           │
│                 ┆               ┆                 ┆            ┆ f64             ┆               │
╞═════════════════╪═══════════════╪═════════════════╪════════════╪═════════════════╪═══════════════╡
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 5.3             ┆ s24529531     │
│ Pro             ┆               ┆ 10:25:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 5.6             ┆ s24529531     │
│ Pro             ┆               ┆ 10:40:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 6.5             ┆ s24529531     │
│ Pro             ┆               ┆ 10:55:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 7.1             ┆ s24529531     │
│ Pro             ┆               ┆ 11:10:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 6.7             ┆ s24529531     │
│ Pro             ┆               ┆ 11:25:00        ┆            ┆                 ┆               │
└─────────────────┴───────────────┴─────────────────┴────────────┴─────────────────┴───────────────┘

Accessing Physical Activity data.

In [42]:
daily_activity = ds.get_aggregated_activity_frame()
daily_activity.head()

shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ participa ┆ vo2       ┆ spo2      ┆ activeZon ┆ … ┆ FairlyAct ┆ LightlyAc ┆ Activitie ┆ activity │
│ ntId      ┆ ---       ┆ ---       ┆ es        ┆   ┆ iveMinute ┆ tiveMinut ┆ s         ┆ _date    │
│ ---       ┆ struct[1] ┆ struct[3] ┆ ---       ┆   ┆ s         ┆ es        ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆ struct[4] ┆   ┆ ---       ┆ ---       ┆ list[stru ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ i64       ┆ ct[16]]   ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s24328102 ┆ {"28-32"} ┆ null      ┆ {27,0,6,2 ┆ … ┆ 2         ┆ 295       ┆ [{"Swim", ┆ 2024-04- │
│ 1         ┆           ┆           ┆ 1}        ┆   ┆           ┆           ┆ 626080858 ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 96,0,80,1 ┆ 00:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 638…      ┆          │
│ s24328102 ┆ {"27-31"} ┆ {93.9,96. ┆ {11,0,0,1 ┆ … ┆ 12        ┆ 200       ┆ [{"Walk", ┆ 2024-04- │
│ 1         ┆           ┆ 2,90.8}   ┆ 1}        ┆   ┆           ┆           ┆ 626209426 ┆ 06       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 38,6936,4 ┆ 00:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 17,…      ┆          │
│ s24328102 ┆ {"27-31"} ┆ {95.4,96. ┆ {9,0,0,9} ┆ … ┆ 15        ┆ 205       ┆ [{"Walk", ┆ 2024-04- │
│ 1         ┆           ┆ 1,95.4}   ┆           ┆   ┆           ┆           ┆ 626418022 ┆ 07       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 40,4848,3 ┆ 00:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 05,…      ┆          │
│ s24328102 ┆ {"27-31"} ┆ {95.1,96. ┆ {79,0,42, ┆ … ┆ 20        ┆ 327       ┆ [{"Walk", ┆ 2024-04- │
│ 1         ┆           ┆ 7,93.0}   ┆ 37}       ┆   ┆           ┆           ┆ 526225563 ┆ 08       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 984856600 ┆ 00:00:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0,2…      ┆          │
│ s24328102 ┆ {"28-32"} ┆ {94.2,96. ┆ {29,0,4,2 ┆ … ┆ 22        ┆ 331       ┆ []        ┆ 2024-04- │
│ 1         ┆           ┆ 6,91.0}   ┆ 5}        ┆   ┆           ┆           ┆           ┆ 09       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [43]:
daily_activity.explode("Activities").unnest("Activities").filter(pl.col("name").is_not_null()).head()

shape: (5, 36)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ participa ┆ vo2       ┆ spo2      ┆ activeZon ┆ … ┆ activityP ┆ hasActive ┆ distance ┆ activity_ │
│ ntId      ┆ ---       ┆ ---       ┆ es        ┆   ┆ arentName ┆ ZoneMinut ┆ ---      ┆ date      │
│ ---       ┆ struct[1] ┆ struct[3] ┆ ---       ┆   ┆ ---       ┆ es        ┆ f64      ┆ ---       │
│ str       ┆           ┆           ┆ struct[4] ┆   ┆ str       ┆ ---       ┆          ┆ datetime[ │
│           ┆           ┆           ┆           ┆   ┆           ┆ bool      ┆          ┆ μs]       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ s24328102 ┆ {"28-32"} ┆ null      ┆ {27,0,6,2 ┆ … ┆ Swim      ┆ true      ┆ 0.375    ┆ 2024-04-0 │
│ 1         ┆           ┆           ┆ 1}        ┆   ┆           ┆           ┆          ┆ 5         │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 00:00:00  │
│ s24328102 ┆ {"27-31"} ┆ {93.9,96. ┆ {11,0,0,1 ┆ … ┆ Walk      ┆ true      ┆ null     ┆ 2024-04-0 │
│ 1         ┆           ┆ 2,90.8}   ┆ 1}        ┆   ┆           ┆           ┆          ┆ 6         │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 00:00:00  │
│ s24328102 ┆ {"27-31"} ┆ {95.4,96. ┆ {9,0,0,9} ┆ … ┆ Walk      ┆ true      ┆ null     ┆ 2024-04-0 │
│ 1         ┆           ┆ 1,95.4}   ┆           ┆   ┆           ┆           ┆          ┆ 7         │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 00:00:00  │
│ s24328102 ┆ {"27-31"} ┆ {95.1,96. ┆ {79,0,42, ┆ … ┆ Walk      ┆ true      ┆ null     ┆ 2024-04-0 │
│ 1         ┆           ┆ 7,93.0}   ┆ 37}       ┆   ┆           ┆           ┆          ┆ 8         │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 00:00:00  │
│ s24328102 ┆ {"28-32"} ┆ {95.5,98. ┆ {134,0,50 ┆ … ┆ Walk      ┆ true      ┆ null     ┆ 2024-04-1 │
│ 1         ┆           ┆ 7,91.8}   ┆ ,84}      ┆   ┆           ┆           ┆          ┆ 0         │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 00:00:00  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

One-liner to return CGM/activity/analysis/visit together.

In [44]:
all_dfs = ds.get_aggregated_frames()
all_dfs[0].shape

(184652, 6)

In [45]:
all_dfs[1].shape

(8049, 21)

Access food data.

In [46]:
food = ds.get_aggregated_food_frame()
food.head()

shape: (5, 5)
┌─────────────────────────┬─────────────────────────────────┬───────────┬──────────┬───────────────┐
│ date                    ┆ foodId                          ┆ meal      ┆ quantity ┆ participantId │
│ ---                     ┆ ---                             ┆ ---       ┆ ---      ┆ ---           │
│ datetime[μs]            ┆ str                             ┆ str       ┆ f64      ┆ str           │
╞═════════════════════════╪═════════════════════════════════╪═══════════╪══════════╪═══════════════╡
│ 2024-06-05 03:19:04.192 ┆ ea557e7b-eb73-4a69-8b0d-dfeb0f… ┆ Breakfast ┆ 50.0     ┆ s24529531     │
│ 2024-06-06 06:00:00     ┆ 670bb123-a3bd-4457-91e1-36ef61… ┆ Breakfast ┆ 25.0     ┆ s24529531     │
│ 2024-06-06 06:00:00     ┆ d48c01b4-64bc-40c5-87c8-d395d0… ┆ Breakfast ┆ 20.0     ┆ s24529531     │
│ 2024-06-06 06:00:00     ┆ 504a753e-ed63-4820-b115-68b93d… ┆ Breakfast ┆ 100.0    ┆ s24529531     │
│ 2024-06-06 11:00:00     ┆ ae93e940-4031-4595-ac04-a0aa42… ┆ Lunch     ┆ 350.0    ┆ s24529531     │
└─────────────────────────┴─────────────────────────────────┴───────────┴──────────┴───────────────┘

In [47]:
macronutrients = ds.macronutrients_frame()
macronutrients.head()

shape: (5, 7)
┌────────────────────────────────┬──────────────────┬──────────┬────────┬──────────┬────────┬──────┐
│ foodId                         ┆ name             ┆ calories ┆ carbs  ┆ proteins ┆ fats   ┆ unit │
│ ---                            ┆ ---              ┆ ---      ┆ ---    ┆ ---      ┆ ---    ┆ ---  │
│ str                            ┆ str              ┆ f64      ┆ f64    ┆ f64      ┆ f64    ┆ str  │
╞════════════════════════════════╪══════════════════╪══════════╪════════╪══════════╪════════╪══════╡
│ 851de7d1-64a4-4f29-8646-46ac6c ┆ CUKURS           ┆ 405.9    ┆ 99.9   ┆ 0.0      ┆ 0.0    ┆ g    │
│ …                              ┆                  ┆          ┆        ┆          ┆        ┆      │
│ c54a8a4d-07dd-484b-ba91-acc355 ┆ FRUKTOZE         ┆ 405.5    ┆ 99.8   ┆ 0.0      ┆ 0.0    ┆ g    │
│ …                              ┆                  ┆          ┆        ┆          ┆        ┆      │
│ 81ff2ec8-c528-433e-aecc-937981 ┆ SĪRUPS           ┆ 301.48   ┆ 74.1   ┆ 0.1      ┆ 0.0    ┆ ml   │
│ …                              ┆                  ┆          ┆        ┆          ┆        ┆      │
│ e7fa9b61-2aa6-47ba-a9ba-dad304 ┆ MEDUS            ┆ 330.33   ┆ 80.8   ┆ 0.5      ┆ 0.0    ┆ g    │
│ …                              ┆                  ┆          ┆        ┆          ┆        ┆      │
│ 9b703a46-6b24-49af-9a39-f3a1d7 ┆ ŠOKOLĀDE, VIDĒJĀ ┆ 542.58   ┆ 47.774 ┆ 9.58     ┆ 34.362 ┆ g    │
│ …                              ┆                  ┆          ┆        ┆          ┆        ┆      │
└────────────────────────────────┴──────────────────┴──────────┴────────┴──────────┴────────┴──────┘

Access subject-level data.

In [48]:
test_id = subjects[0].participantId
test_subj = ds.get_subject(test_id) # or ds[test_id]

In [49]:
test_subj.cgm[:5]

[CGMEntry(device='FreeStyle Libre Pro', serialNumber='JRMA246-K0188', deviceTimestamp=datetime.datetime(2024, 6, 5, 10, 25), recordType=0, historicGlucoseMmolL=5.3),
 CGMEntry(device='FreeStyle Libre Pro', serialNumber='JRMA246-K0188', deviceTimestamp=datetime.datetime(2024, 6, 5, 10, 40), recordType=0, historicGlucoseMmolL=5.6),
 CGMEntry(device='FreeStyle Libre Pro', serialNumber='JRMA246-K0188', deviceTimestamp=datetime.datetime(2024, 6, 5, 10, 55), recordType=0, historicGlucoseMmolL=6.5),
 CGMEntry(device='FreeStyle Libre Pro', serialNumber='JRMA246-K0188', deviceTimestamp=datetime.datetime(2024, 6, 5, 11, 10), recordType=0, historicGlucoseMmolL=7.1),
 CGMEntry(device='FreeStyle Libre Pro', serialNumber='JRMA246-K0188', deviceTimestamp=datetime.datetime(2024, 6, 5, 11, 25), recordType=0, historicGlucoseMmolL=6.7)]

In [50]:
test_subj.get_cgm_frame()

shape: (2_678, 6)
┌─────────────────┬───────────────┬─────────────────┬────────────┬─────────────────┬───────────────┐
│ device          ┆ serialNumber  ┆ deviceTimestamp ┆ recordType ┆ historicGlucose ┆ participantId │
│ ---             ┆ ---           ┆ ---             ┆ ---        ┆ MmolL           ┆ ---           │
│ str             ┆ str           ┆ datetime[μs]    ┆ i64        ┆ ---             ┆ str           │
│                 ┆               ┆                 ┆            ┆ f64             ┆               │
╞═════════════════╪═══════════════╪═════════════════╪════════════╪═════════════════╪═══════════════╡
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 5.3             ┆ s24529531     │
│ Pro             ┆               ┆ 10:25:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 5.6             ┆ s24529531     │
│ Pro             ┆               ┆ 10:40:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 6.5             ┆ s24529531     │
│ Pro             ┆               ┆ 10:55:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 7.1             ┆ s24529531     │
│ Pro             ┆               ┆ 11:10:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-06-05      ┆ 0          ┆ 6.7             ┆ s24529531     │
│ Pro             ┆               ┆ 11:25:00        ┆            ┆                 ┆               │
│ …               ┆ …             ┆ …               ┆ …          ┆ …               ┆ …             │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-08-14      ┆ 0          ┆ 5.2             ┆ s24529531     │
│ Pro             ┆               ┆ 08:08:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-08-14      ┆ 0          ┆ 5.2             ┆ s24529531     │
│ Pro             ┆               ┆ 08:23:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-08-14      ┆ 0          ┆ 5.2             ┆ s24529531     │
│ Pro             ┆               ┆ 08:38:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-08-14      ┆ 0          ┆ 5.2             ┆ s24529531     │
│ Pro             ┆               ┆ 08:53:00        ┆            ┆                 ┆               │
│ FreeStyle Libre ┆ JRMA246-K0188 ┆ 2024-08-14      ┆ 0          ┆ 5.3             ┆ s24529531     │
│ Pro             ┆               ┆ 09:08:00        ┆            ┆                 ┆               │
└─────────────────┴───────────────┴─────────────────┴────────────┴─────────────────┴───────────────┘

In [51]:
test_subj.get_analysis_frame()

shape: (3, 38)
┌──────────────┬───────┬──────────────┬───────────┬───┬───────┬────────┬─────────────┬─────────────┐
│ formId       ┆ HbA1c ┆ Fasting_bloo ┆ C_peptide ┆ … ┆ IL_10 ┆ Leptin ┆ missingData ┆ participant │
│ ---          ┆ ---   ┆ d_glucose    ┆ ---       ┆   ┆ ---   ┆ ---    ┆ ---         ┆ Id          │
│ str          ┆ f64   ┆ ---          ┆ f64       ┆   ┆ f64   ┆ f64    ┆ bool        ┆ ---         │
│              ┆       ┆ f64          ┆           ┆   ┆       ┆        ┆             ┆ str         │
╞══════════════╪═══════╪══════════════╪═══════════╪═══╪═══════╪════════╪═════════════╪═════════════╡
│ VISIT1_ANALY ┆ null  ┆ 5.41         ┆ 1.51      ┆ … ┆ 22.17 ┆ 1500.2 ┆ false       ┆ s24529531   │
│ SISRESULT_UN ┆       ┆              ┆           ┆   ┆       ┆        ┆             ┆             │
│ IL           ┆       ┆              ┆           ┆   ┆       ┆        ┆             ┆             │
│ VISIT2_ANALY ┆ 5.31  ┆ 5.4          ┆ null      ┆ … ┆ 15.97 ┆ 2068.9 ┆ false       ┆ s24529531   │
│ SISRESULT_UN ┆       ┆              ┆           ┆   ┆       ┆        ┆             ┆             │
│ IL           ┆       ┆              ┆           ┆   ┆       ┆        ┆             ┆             │
│ VISIT3_ANALY ┆ 5.35  ┆ 5.29         ┆ 1.85      ┆ … ┆ 25.5  ┆ 1836.7 ┆ false       ┆ s24529531   │
│ SISRESULT_UN ┆       ┆              ┆           ┆   ┆       ┆        ┆             ┆             │
│ IL           ┆       ┆              ┆           ┆   ┆       ┆        ┆             ┆             │
└──────────────┴───────┴──────────────┴───────────┴───┴───────┴────────┴─────────────┴─────────────┘

In [52]:
test_subj.get_visit_frame()

shape: (3, 19)
┌──────┬───────────┬──────┬──────────┬───┬─────────────┬───────────────┬────────────┬─────────┐
│ Age  ┆ BloodTest ┆ CGM  ┆ Distance ┆ … ┆ missingData ┆ participantId ┆ recall_24h ┆ visitId │
│ ---  ┆ ---       ┆ ---  ┆ ---      ┆   ┆ ---         ┆ ---           ┆ ---        ┆ ---     │
│ f64  ┆ str       ┆ str  ┆ f64      ┆   ┆ bool        ┆ str           ┆ str        ┆ str     │
╞══════╪═══════════╪══════╪══════════╪═══╪═════════════╪═══════════════╪════════════╪═════════╡
│ 55.0 ┆ Yes       ┆ Yes  ┆ 658.0    ┆ … ┆ false       ┆ s24529531     ┆ Yes        ┆ visit1  │
│ 55.0 ┆ Yes       ┆ Yes  ┆ 647.0    ┆ … ┆ false       ┆ s24529531     ┆ Yes        ┆ visit2  │
│ 55.0 ┆ Yes       ┆ null ┆ 627.0    ┆ … ┆ false       ┆ s24529531     ┆ Yes        ┆ visit3  │
└──────┴───────────┴──────┴──────────┴───┴─────────────┴───────────────┴────────────┴─────────┘

In [53]:
test_subj.get_food_frame().sort("date")

shape: (165, 5)
┌─────────────────────────┬─────────────────────────────────┬───────────┬──────────┬───────────────┐
│ date                    ┆ foodId                          ┆ meal      ┆ quantity ┆ participantId │
│ ---                     ┆ ---                             ┆ ---       ┆ ---      ┆ ---           │
│ datetime[μs]            ┆ str                             ┆ str       ┆ f64      ┆ str           │
╞═════════════════════════╪═════════════════════════════════╪═══════════╪══════════╪═══════════════╡
│ 2024-06-05 03:19:04.192 ┆ ea557e7b-eb73-4a69-8b0d-dfeb0f… ┆ Breakfast ┆ 50.0     ┆ s24529531     │
│ 2024-06-05 04:30:00     ┆ 21f4aa25-0b58-4dfb-90aa-10c554… ┆ Breakfast ┆ 50.0     ┆ s24529531     │
│ 2024-06-05 08:00:00     ┆ 1d0371ef-fe6a-4706-9712-b5fdd6… ┆ Breakfast ┆ 100.0    ┆ s24529531     │
│ 2024-06-05 08:00:00     ┆ fc7581f4-7ab6-4d2e-be8a-810fbd… ┆ Breakfast ┆ 10.0     ┆ s24529531     │
│ 2024-06-05 08:00:00     ┆ 53d2b152-6268-4109-9616-4bc60a… ┆ Breakfast ┆ 20.0     ┆ s24529531     │
│ …                       ┆ …                               ┆ …         ┆ …        ┆ …             │
│ 2024-10-03 16:30:00     ┆ 16a0a62d-d550-4b21-af5a-52cb7b… ┆ Dinner    ┆ 30.0     ┆ s24529531     │
│ 2024-10-03 16:30:00     ┆ 384b80db-5dc4-4ab8-aff1-a92af6… ┆ Dinner    ┆ 130.0    ┆ s24529531     │
│ 2024-10-03 16:30:00     ┆ 8887c292-6d98-46d6-b97d-e6168b… ┆ Dinner    ┆ 25.0     ┆ s24529531     │
│ 2024-10-03 16:30:00     ┆ 3937e175-52cb-4fec-b586-8e8e9c… ┆ Dinner    ┆ 75.0     ┆ s24529531     │
│ 2024-10-03 16:30:00     ┆ a21b85b1-1000-4ca2-a085-e3ffa1… ┆ Dinner    ┆ 2000.0   ┆ s24529531     │
└─────────────────────────┴─────────────────────────────────┴───────────┴──────────┴───────────────┘

In [54]:
test_subj.activities[:5]

[Activity(data=ActivityData(vo2=VO2Data(vo2Max='31-35'), spo2=None, activeZones=ActiveZonesData(activeZoneMinutes=28, peakActiveZoneMinutes=0, cardioActiveZoneMinutes=0, fatBurnActiveZoneMinutes=28), activities=None, activitySummary=ActivitySummaryWrapper(Summary=ActivitySummary(Steps=12603, Floors=None, Distances=[Distance(Activity='total', Distance=8.6022), Distance(Activity='tracker', Distance=8.6022), Distance(Activity='sedentaryActive', Distance=0.0), Distance(Activity='lightlyActive', Distance=2.7038), Distance(Activity='moderatelyActive', Distance=2.2972), Distance(Activity='veryActive', Distance=3.6012), Distance(Activity='loggedActivities', Distance=0.0)], Elevation=None, CaloriesBMR=1498, CaloriesOut=2420, HeartRateZones=[HeartRateZone(max=118, min=30, name='Out of Range', minutes=1412, caloriesOut=2260.159825), HeartRateZone(max=141, min=119, name='Fat Burn', minutes=28, caloriesOut=159.36305000000002), HeartRateZone(max=171, min=142, name='Cardio', minutes=0, caloriesOut=0.0), HeartRateZone(max=220, min=172, name='Peak', minutes=0, caloriesOut=0.0)], ActivityCalories=1232, MarginalCalories=836, RestingHeartRate=72.0, SedentaryMinutes=981, VeryActiveMinutes=47, FairlyActiveMinutes=40, LightlyActiveMinutes=200), Activities=[SummaryActivity(name='Walk', logId=6492882413753627000, steps=5628, calories=349, duration=3585000, startDate='2024-10-03', startTime='17:47', activityId=90013, isFavorite=False, description='Walking less than 2 mph, strolling very slowly', hasStartTime=True, lastModified=datetime.datetime(2024, 10, 3, 15, 51, 10, 82000, tzinfo=TzInfo(0)), activityParentId=90013, activityParentName='Walk', hasActiveZoneMinutes=True, distance=None)])), activity_date=datetime.datetime(2024, 10, 3, 0, 0, tzinfo=TzInfo(0))),
 Activity(data=ActivityData(vo2=VO2Data(vo2Max='31-35'), spo2=None, activeZones=ActiveZonesData(activeZoneMinutes=1, peakActiveZoneMinutes=0, cardioActiveZoneMinutes=0, fatBurnActiveZoneMinutes=1), activities=None, activitySummary=ActivitySummaryWrapper(Summary=ActivitySummary(Steps=4007, Floors=None, Distances=[Distance(Activity='total', Distance=2.726), Distance(Activity='tracker', Distance=2.726), Distance(Activity='sedentaryActive', Distance=0.0), Distance(Activity='lightlyActive', Distance=1.3203), Distance(Activity='moderatelyActive', Distance=1.0516), Distance(Activity='veryActive', Distance=0.3541), Distance(Activity='loggedActivities', Distance=0.0)], Elevation=None, CaloriesBMR=1498, CaloriesOut=1829, HeartRateZones=[], ActivityCalories=455, MarginalCalories=295, RestingHeartRate=None, SedentaryMinutes=1222, VeryActiveMinutes=5, FairlyActiveMinutes=13, LightlyActiveMinutes=100), Activities=[])), activity_date=datetime.datetime(2024, 9, 21, 0, 0, tzinfo=TzInfo(0))),
 Activity(data=ActivityData(vo2=VO2Data(vo2Max='31-35'), spo2=None, activeZones=ActiveZonesData(activeZoneMinutes=10, peakActiveZoneMinutes=0, cardioActiveZoneMinutes=0, fatBurnActiveZoneMinutes=10), activities=[DetailedActivity(activeDuration=973000, activityLevel=[ActivityLevel(minutes=0, name='sedentary'), ActivityLevel(minutes=17, name='lightly'), ActivityLevel(minutes=0, name='fairly'), ActivityLevel(minutes=0, name='very')], activityName='Walk', activityTypeId=90013, averageHeartRate=105, calories=80, dateOfActivity='09-28-2024', distance=0.0, distanceUnit=None, duration=973000, elevationGain=0.0, lastModified=datetime.datetime(2024, 9, 28, 16, 49, 41, 383000, tzinfo=TzInfo(0)), logId=7354824211569284000, logType='auto_detected', originalDuration=973000, originalStartTime=datetime.datetime(2024, 9, 28, 13, 29, 48, tzinfo=TzInfo(10800)), pace=0.0, speed=0.0, startTime=datetime.datetime(2024, 9, 28, 13, 29, 48, tzinfo=TzInfo(10800)), steps=1153, tcxLink='https://api.fitbit.com/1/user/-/activities/7354824211569284160.tcx'), DetailedActivity(activeDuration=1229000, activityLevel=[ActivityLevel(minutes=0, name='sedentary'), ActivityLevel(minutes=8, name='lightly'), ActivityLevel(minutes=12, name='fairly'), ActivityLevel(minutes=0, name='very')], activityName='Walk', activityTypeId=90013, averageHeartRate=108, calories=101, dateOfActivity='09-28-2024', distance=0.0, distanceUnit=None, duration=1229000, elevationGain=0.0, lastModified=datetime.datetime(2024, 9, 28, 16, 49, 42, 283000, tzinfo=TzInfo(0)), logId=4638106737492110000, logType='auto_detected', originalDuration=1229000, originalStartTime=datetime.datetime(2024, 9, 28, 14, 31, 14, tzinfo=TzInfo(10800)), pace=0.0, speed=0.0, startTime=datetime.datetime(2024, 9, 28, 14, 31, 14, tzinfo=TzInfo(10800)), steps=1456, tcxLink='https://api.fitbit.com/1/user/-/activities/4638106737492110632.tcx'), DetailedActivity(activeDuration=2919000, activityLevel=[ActivityLevel(minutes=0, name='sedentary'), ActivityLevel(minutes=17, name='lightly'), ActivityLevel(minutes=30, name='fairly'), ActivityLevel(minutes=1, name='very')], activityName='Walk', activityTypeId=90013, averageHeartRate=106, calories=228, dateOfActivity='09-28-2024', distance=0.0, distanceUnit=None, duration=2919000, elevationGain=0.0, lastModified=datetime.datetime(2024, 9, 28, 16, 49, 42, 992000, tzinfo=TzInfo(0)), logId=8577589713336255000, logType='auto_detected', originalDuration=2919000, originalStartTime=datetime.datetime(2024, 9, 28, 16, 45, 12, tzinfo=TzInfo(10800)), pace=0.0, speed=0.0, startTime=datetime.datetime(2024, 9, 28, 16, 45, 12, tzinfo=TzInfo(10800)), steps=3196, tcxLink='https://api.fitbit.com/1/user/-/activities/8577589713336255248.tcx')], activitySummary=ActivitySummaryWrapper(Summary=ActivitySummary(Steps=13942, Floors=None, Distances=[Distance(Activity='total', Distance=9.5329), Distance(Activity='tracker', Distance=9.5329), Distance(Activity='sedentaryActive', Distance=0.0), Distance(Activity='lightlyActive', Distance=4.5523), Distance(Activity='moderatelyActive', Distance=4.8438), Distance(Activity='veryActive', Distance=0.1368), Distance(Activity='loggedActivities', Distance=0.0)], Elevation=None, CaloriesBMR=1498, CaloriesOut=2504, HeartRateZones=[HeartRateZone(max=119, min=30, name='Out of Range', minutes=1430, caloriesOut=2455.435675), HeartRateZone(max=142, min=120, name='Fat Burn', minutes=10, caloriesOut=48.257825000000004), HeartRateZone(max=171, min=143, name='Cardio', minutes=0, caloriesOut=0.0), HeartRateZone(max=220, min=172, name='Peak', minutes=0, caloriesOut=0.0)], ActivityCalories=1372, MarginalCalories=901, RestingHeartRate=74.0, SedentaryMinutes=992, VeryActiveMinutes=1, FairlyActiveMinutes=46, LightlyActiveMinutes=296), Activities=[SummaryActivity(name='Walk', logId=7354824211569284000, steps=1153, calories=80, duration=973000, startDate='2024-09-28', startTime='13:29', activityId=90013, isFavorite=False, description='Walking less than 2 mph, strolling very slowly', hasStartTime=True, lastModified=datetime.datetime(2024, 9, 28, 16, 49, 41, 383000, tzinfo=TzInfo(0)), activityParentId=90013, activityParentName='Walk', hasActiveZoneMinutes=True, distance=None), SummaryActivity(name='Walk', logId=4638106737492110000, steps=1456, calories=101, duration=1229000, startDate='2024-09-28', startTime='14:31', activityId=90013, isFavorite=False, description='Walking less than 2 mph, strolling very slowly', hasStartTime=True, lastModified=datetime.datetime(2024, 9, 28, 16, 49, 42, 283000, tzinfo=TzInfo(0)), activityParentId=90013, activityParentName='Walk', hasActiveZoneMinutes=True, distance=None), SummaryActivity(name='Walk', logId=8577589713336255000, steps=3196, calories=228, duration=2919000, startDate='2024-09-28', startTime='16:45', activityId=90013, isFavorite=False, description='Walking less than 2 mph, strolling very slowly', hasStartTime=True, lastModified=datetime.datetime(2024, 9, 28, 16, 49, 42, 992000, tzinfo=TzInfo(0)), activityParentId=90013, activityParentName='Walk', hasActiveZoneMinutes=True, distance=None)])), activity_date=datetime.datetime(2024, 9, 28, 0, 0, tzinfo=TzInfo(0))),
 Activity(data=ActivityData(vo2=VO2Data(vo2Max='31-35'), spo2=SPO2Data(Avg=95.8, Max=99.6, Min=92.9), activeZones=ActiveZonesData(activeZoneMinutes=11, peakActiveZoneMinutes=0, cardioActiveZoneMinutes=4, fatBurnActiveZoneMinutes=7), activities=None, activitySummary=ActivitySummaryWrapper(Summary=ActivitySummary(Steps=5058, Floors=None, Distances=[Distance(Activity='total', Distance=3.4509), Distance(Activity='tracker', Distance=3.4509), Distance(Activity='sedentaryActive', Distance=0.0), Distance(Activity='lightlyActive', Distance=1.9769), Distance(Activity='moderatelyActive', Distance=0.5956), Distance(Activity='veryActive', Distance=0.8784), Distance(Activity='loggedActivities', Distance=0.0)], Elevation=None, CaloriesBMR=1498, CaloriesOut=2011, HeartRateZones=[HeartRateZone(max=118, min=30, name='Out of Range', minutes=1431, caloriesOut=1951.6362250000002), HeartRateZone(max=141, min=119, name='Fat Burn', minutes=7, caloriesOut=41.626200000000004), HeartRateZone(max=171, min=142, name='Cardio', minutes=2, caloriesOut=17.344250000000002), HeartRateZone(max=220, min=172, name='Peak', minutes=0, caloriesOut=0.0)], ActivityCalories=727, MarginalCalories=469, RestingHeartRate=72.0, SedentaryMinutes=1251, VeryActiveMinutes=12, FairlyActiveMinutes=8, LightlyActiveMinutes=169), Activities=[])), activity_date=datetime.datetime(2024, 10, 2, 0, 0, tzinfo=TzInfo(0))),
 Activity(data=ActivityData(vo2=VO2Data(vo2Max='31-35'), spo2=SPO2Data(Avg=95.5, Max=96.8, Min=94.7), activeZones=ActiveZonesData(activeZoneMinutes=3, peakActiveZoneMinutes=0, cardioActiveZoneMinutes=0, fatBurnActiveZoneMinutes=3), activities=None, activitySummary=ActivitySummaryWrapper(Summary=ActivitySummary(Steps=5078, Floors=None, Distances=[Distance(Activity='total', Distance=3.4674), Distance(Activity='tracker', Distance=3.4674), Distance(Activity='sedentaryActive', Distance=0.0), Distance(Activity='lightlyActive', Distance=2.812), Distance(Activity='moderatelyActive', Distance=0.2899), Distance(Activity='veryActive', Distance=0.3655), Distance(Activity='loggedActivities', Distance=0.0)], Elevation=None, CaloriesBMR=1498, CaloriesOut=1988, HeartRateZones=[HeartRateZone(max=118, min=30, name='Out of Range', minutes=1437, caloriesOut=1971.3270500000003), HeartRateZone(max=142, min=119, name='Fat Burn', minutes=3, caloriesOut=16.732100000000003), HeartRateZone(max=171, min=143, name='Cardio', minutes=0, caloriesOut=0.0), HeartRateZone(max=220, min=172, name='Peak', minutes=0, caloriesOut=0.0)], ActivityCalories=725, MarginalCalories=424, RestingHeartRate=73.0, SedentaryMinutes=1218, VeryActiveMinutes=0, FairlyActiveMinutes=0, LightlyActiveMinutes=222), Activities=[])), activity_date=datetime.datetime(2024, 10, 1, 0, 0, tzinfo=TzInfo(0)))]