This notebook covers post-unification CGM processing on the unified subject-level dataframe. We reshape CGM series across granularities (subject, daily, individual recordings) useful for downstream analyses and run quality checks (duplicates, missing values, coverage, temporal continuity).

In [1]:
import sys
import os

parent_dir = os.path.abspath("../")
sys.path.append(parent_dir)

import polars as pl
from chronoindex.dataset_loader import load_datasets
from chronoindex.glucose_series_processing.ts_manager import TimeSeriesManager
from chronoindex.dataset_unifier import UnifiedCGMDataset, UnifiedFoodData, UnifiedPhysicalActivityData

In [2]:
datasets, errors = load_datasets(
    config_path= "datasets.toml",
    only=["zhao","praes_unil"]
)
if errors:
    raise RuntimeError(errors)

➡️ Loading datasets.zhao
➡️ Loading datasets.praes_unil

In [3]:
unified = UnifiedCGMDataset(
    datasets
    )

df = unified.unified_data   # same as unified.cgm_data
df.head()

shape: (5, 4)
┌─────────────────┬─────────────────────────┬─────────────────────────────────┬─────────┐
│ Id              ┆ CGM                     ┆ CGMTime                         ┆ dataset │
│ ---             ┆ ---                     ┆ ---                             ┆ ---     │
│ str             ┆ list[f64]               ┆ list[datetime[μs]]              ┆ str     │
╞═════════════════╪═════════════════════════╪═════════════════════════════════╪═════════╡
│ 2000_0_20201230 ┆ [138.6, 120.6, … 88.2]  ┆ [2020-12-30 13:54:00, 2020-12-… ┆ zhao    │
│ 2001_0_20201102 ┆ [102.6, 97.2, … 136.8]  ┆ [2020-11-02 09:40:00, 2020-11-… ┆ zhao    │
│ 2001_1_20201117 ┆ [151.2, 145.8, … 180.0] ┆ [2020-11-17 09:19:00, 2020-11-… ┆ zhao    │
│ 2002_0_20210513 ┆ [257.4, 246.6, … 217.8] ┆ [2021-05-13 16:22:00, 2021-05-… ┆ zhao    │
│ 2003_0_20210615 ┆ [264.6, 262.8, … 180.0] ┆ [2021-06-15 17:20:00, 2021-06-… ┆ zhao    │
└─────────────────┴─────────────────────────┴─────────────────────────────────┴─────────┘

In [4]:
ts_manager = TimeSeriesManager(df)
ts_manager.to_individual_recordings(patient_identifier_col="Id")
recordings_df = ts_manager.df
recordings_df

shape: (296_212, 4)
┌─────────────────┬─────────┬─────────────────────┬────────────┐
│ Id              ┆ CGM     ┆ CGMTime             ┆ dataset    │
│ ---             ┆ ---     ┆ ---                 ┆ ---        │
│ str             ┆ f64     ┆ datetime[μs]        ┆ str        │
╞═════════════════╪═════════╪═════════════════════╪════════════╡
│ s241081147      ┆ 97.2972 ┆ 2024-10-10 11:23:00 ┆ praes_unil │
│ s241081147      ┆ 95.4954 ┆ 2024-10-10 11:38:00 ┆ praes_unil │
│ s241081147      ┆ 95.4954 ┆ 2024-10-10 11:53:00 ┆ praes_unil │
│ s241081147      ┆ 95.4954 ┆ 2024-10-10 12:08:00 ┆ praes_unil │
│ s241081147      ┆ 93.6936 ┆ 2024-10-10 12:23:00 ┆ praes_unil │
│ …               ┆ …       ┆ …                   ┆ …          │
│ 2099_0_20201116 ┆ 97.2    ┆ 2020-11-30 07:47:00 ┆ zhao       │
│ 2099_0_20201116 ┆ 93.6    ┆ 2020-11-30 08:02:00 ┆ zhao       │
│ 2099_0_20201116 ┆ 90.0    ┆ 2020-11-30 08:17:00 ┆ zhao       │
│ 2099_0_20201116 ┆ 88.2    ┆ 2020-11-30 08:32:00 ┆ zhao       │
│ 2099_0_20201116 ┆ 86.4    ┆ 2020-11-30 08:47:00 ┆ zhao       │
└─────────────────┴─────────┴─────────────────────┴────────────┘

In [5]:
ts_manager = TimeSeriesManager(df)
ts_manager.to_daily_df(patient_identifier_col="Id", temporal_resolution="hourly")
print(ts_manager.df)

shape: (74_261, 6)
┌────────────┬─────────────────┬──────┬────────────┬───────────────────────┬───────────────────────┐
│ dataset    ┆ Id              ┆ hour ┆ date       ┆ CGM                   ┆ CGMTime               │
│ ---        ┆ ---             ┆ ---  ┆ ---        ┆ ---                   ┆ ---                   │
│ str        ┆ str             ┆ i8   ┆ date       ┆ list[f64]             ┆ list[datetime[μs]]    │
╞════════════╪═════════════════╪══════╪════════════╪═══════════════════════╪═══════════════════════╡
│ praes_unil ┆ s24425831       ┆ 13   ┆ 2024-07-02 ┆ [97.2972, 100.9008, … ┆ [2024-07-02 13:04:00, │
│            ┆                 ┆      ┆            ┆ 104.5044…             ┆ 2024-07-…             │
│ praes_unil ┆ s24111587       ┆ 4    ┆ 2025-01-25 ┆ [81.081, 81.081, …    ┆ [2025-01-25 04:00:00, │
│            ┆                 ┆      ┆            ┆ 82.8828]              ┆ 2025-01-…             │
│ zhao       ┆ 2055_0_20210524 ┆ 10   ┆ 2021-05-24 ┆ [199.8, 190.8, 183.6] ┆ [2021-05-24 10:21:00, │
│            ┆                 ┆      ┆            ┆                       ┆ 2021-05-…             │
│ zhao       ┆ 2089_0_20201019 ┆ 3    ┆ 2020-10-25 ┆ [126.0, 127.8, …      ┆ [2020-10-25 03:06:00, │
│            ┆                 ┆      ┆            ┆ 126.0]                ┆ 2020-10-…             │
│ zhao       ┆ 2068_0_20210616 ┆ 23   ┆ 2021-06-16 ┆ [115.2, 113.4, …      ┆ [2021-06-16 23:11:00, │
│            ┆                 ┆      ┆            ┆ 100.8]                ┆ 2021-06-…             │
│ …          ┆ …               ┆ …    ┆ …          ┆ …                     ┆ …                     │
│ praes_unil ┆ s24717545       ┆ 5    ┆ 2024-08-03 ┆ [97.2972, 97.2972, …  ┆ [2024-08-03 05:04:00, │
│            ┆                 ┆      ┆            ┆ 97.2972]              ┆ 2024-08-…             │
│ praes_unil ┆ s24627621       ┆ 3    ┆ 2024-09-18 ┆ [91.8918, 91.8918, …  ┆ [2024-09-18 03:07:00, │
│            ┆                 ┆      ┆            ┆ 91.8918]              ┆ 2024-09-…             │
│ praes_unil ┆ s24121090       ┆ 21   ┆ 2025-03-07 ┆ [113.5134, 126.126, … ┆ [2025-03-07 21:05:00, │
│            ┆                 ┆      ┆            ┆ 115.3152…             ┆ 2025-03-…             │
│ zhao       ┆ 2027_0_20210521 ┆ 10   ┆ 2021-05-24 ┆ [244.8, 243.0, …      ┆ [2021-05-24 10:06:00, │
│            ┆                 ┆      ┆            ┆ 246.6]                ┆ 2021-05-…             │
│ praes_unil ┆ s24625553       ┆ 6    ┆ 2024-09-09 ┆ [95.4954, 91.8918, …  ┆ [2024-09-09 06:14:00, │
│            ┆                 ┆      ┆            ┆ 100.9008]             ┆ 2024-09-…             │
└────────────┴─────────────────┴──────┴────────────┴───────────────────────┴───────────────────────┘

In [6]:
ts_manager.to_subject_df(patient_identifier_col="Id")
print(ts_manager.df)

shape: (185, 4)
┌────────────┬─────────────────┬────────────────────────────────┬─────────────────────────────────┐
│ dataset    ┆ Id              ┆ CGM                            ┆ CGMTime                         │
│ ---        ┆ ---             ┆ ---                            ┆ ---                             │
│ str        ┆ str             ┆ list[f64]                      ┆ list[datetime[μs]]              │
╞════════════╪═════════════════╪════════════════════════════════╪═════════════════════════════════╡
│ zhao       ┆ 2034_0_20210624 ┆ [246.6, 250.2, … 97.2]         ┆ [2021-06-24 12:31:00, 2021-06-… │
│ praes_unil ┆ s24711712       ┆ [88.2882, 104.5044, … 84.6846] ┆ [2024-07-17 13:03:00, 2024-07-… │
│ praes_unil ┆ s25116857       ┆ [91.8918, 93.6936, … 95.4954]  ┆ [2025-02-11 10:18:00, 2025-02-… │
│ zhao       ┆ 2064_0_20210608 ┆ [145.8, 145.8, … 219.6]        ┆ [2021-06-08 14:55:00, 2021-06-… │
│ zhao       ┆ 2099_0_20201116 ┆ [86.4, 77.4, … 86.4]           ┆ [2020-11-16 12:47:00, 2020-11-… │
│ …          ┆ …               ┆ …                              ┆ …                               │
│ zhao       ┆ 2001_1_20201117 ┆ [151.2, 145.8, … 180.0]        ┆ [2020-11-17 09:19:00, 2020-11-… │
│ zhao       ┆ 2068_0_20210616 ┆ [131.4, 124.2, … 102.6]        ┆ [2021-06-16 10:41:00, 2021-06-… │
│ praes_unil ┆ s24516746       ┆ [75.6756, 72.072, … 109.9098]  ┆ [2024-05-21 14:16:00, 2024-05-… │
│ zhao       ┆ 2077_0_20210803 ┆ [104.4, 97.2, … 43.2]          ┆ [2021-08-03 15:58:00, 2021-08-… │
│ praes_unil ┆ s24417854       ┆ [88.2882, 88.2882, … 86.4864]  ┆ [2024-04-24 12:47:00, 2024-04-… │
└────────────┴─────────────────┴────────────────────────────────┴─────────────────────────────────┘

In [7]:
ts_manager = TimeSeriesManager(df)
ts_manager.to_daily_df(patient_identifier_col="Id", temporal_resolution="day_night")
print(ts_manager.df)

shape: (6_424, 6)
┌────────────┬─────────────────┬───────┬────────────┬───────────────────────┬──────────────────────┐
│ dataset    ┆ Id              ┆ AM_PM ┆ date       ┆ CGM                   ┆ CGMTime              │
│ ---        ┆ ---             ┆ ---   ┆ ---        ┆ ---                   ┆ ---                  │
│ str        ┆ str             ┆ bool  ┆ date       ┆ list[f64]             ┆ list[datetime[μs]]   │
╞════════════╪═════════════════╪═══════╪════════════╪═══════════════════════╪══════════════════════╡
│ praes_unil ┆ s2412161129     ┆ true  ┆ 2024-12-24 ┆ [102.7026, 95.4954, … ┆ [2024-12-24          │
│            ┆                 ┆       ┆            ┆ 97.2972]              ┆ 13:13:00, 2024-12-…  │
│ zhao       ┆ 2079_0_20210809 ┆ false ┆ 2021-08-10 ┆ [59.4, 75.6, … 127.8] ┆ [2021-08-10          │
│            ┆                 ┆       ┆            ┆                       ┆ 00:04:00, 2021-08-…  │
│ praes_unil ┆ s24111587       ┆ false ┆ 2024-11-30 ┆ [88.2882, 84.6846, …  ┆ [2024-11-30          │
│            ┆                 ┆       ┆            ┆ 127.9278]             ┆ 00:14:00, 2024-11-…  │
│ praes_unil ┆ s251281327      ┆ false ┆ 2025-04-09 ┆ [102.7026, 104.5044,  ┆ [2025-04-09          │
│            ┆                 ┆       ┆            ┆ … 108.108…            ┆ 00:13:00, 2025-04-…  │
│ zhao       ┆ 2021_0_20211013 ┆ false ┆ 2021-10-18 ┆ [203.4, 192.6, …      ┆ [2021-10-18          │
│            ┆                 ┆       ┆            ┆ 192.6]                ┆ 00:14:00, 2021-10-…  │
│ …          ┆ …               ┆ …     ┆ …          ┆ …                     ┆ …                    │
│ praes_unil ┆ s24417115       ┆ true  ┆ 2024-06-21 ┆ [81.081, 81.081, …    ┆ [2024-06-21          │
│            ┆                 ┆       ┆            ┆ 91.8918]              ┆ 13:11:00, 2024-06-…  │
│ praes_unil ┆ s24819759       ┆ false ┆ 2024-09-10 ┆ [99.099, 95.4954, …   ┆ [2024-09-10          │
│            ┆                 ┆       ┆            ┆ 142.3422]             ┆ 00:01:00, 2024-09-…  │
│ praes_unil ┆ s2471878        ┆ false ┆ 2024-07-25 ┆ [90.09, 84.6846, …    ┆ [2024-07-25          │
│            ┆                 ┆       ┆            ┆ 104.5044]             ┆ 00:13:00, 2024-07-…  │
│ praes_unil ┆ s24619922       ┆ true  ┆ 2024-09-05 ┆ [104.5044, 109.9098,  ┆ [2024-09-05          │
│            ┆                 ┆       ┆            ┆ … 91.8918…            ┆ 13:13:00, 2024-09-…  │
│ zhao       ┆ 2001_1_20201117 ┆ true  ┆ 2020-11-29 ┆ [118.8, 129.6, …      ┆ [2020-11-29          │
│            ┆                 ┆       ┆            ┆ 122.4]                ┆ 13:04:00, 2020-11-…  │
└────────────┴─────────────────┴───────┴────────────┴───────────────────────┴──────────────────────┘

In [8]:
ts_manager = TimeSeriesManager(df)
ts_manager.to_daily_df(patient_identifier_col="Id", temporal_resolution="daily")
print(ts_manager.df)

shape: (3_371, 5)
┌────────────┬─────────────────┬────────────┬─────────────────────────┬───────────────────────┐
│ dataset    ┆ Id              ┆ date       ┆ CGM                     ┆ CGMTime               │
│ ---        ┆ ---             ┆ ---        ┆ ---                     ┆ ---                   │
│ str        ┆ str             ┆ date       ┆ list[f64]               ┆ list[datetime[μs]]    │
╞════════════╪═════════════════╪════════════╪═════════════════════════╪═══════════════════════╡
│ praes_unil ┆ s24819736       ┆ 2024-11-11 ┆ [86.4864, 84.6846, …    ┆ [2024-11-11 00:13:00, │
│            ┆                 ┆            ┆ 115.3152]               ┆ 2024-11-…             │
│ praes_unil ┆ s24819759       ┆ 2024-11-15 ┆ [88.2882, 84.6846, …    ┆ [2024-11-15 00:13:00, │
│            ┆                 ┆            ┆ 102.7026]               ┆ 2024-11-…             │
│ praes_unil ┆ s24527852       ┆ 2024-05-31 ┆ [82.8828, 61.2612, …    ┆ [2024-05-31 00:03:00, │
│            ┆                 ┆            ┆ 122.5224]               ┆ 2024-05-…             │
│ zhao       ┆ 2010_0_20220111 ┆ 2022-01-15 ┆ [91.8, 97.2, … 102.6]   ┆ [2022-01-15 00:14:00, │
│            ┆                 ┆            ┆                         ┆ 2022-01-…             │
│ praes_unil ┆ s2453086        ┆ 2024-08-21 ┆ [86.4864, 86.4864, …    ┆ [2024-08-21 00:45:00, │
│            ┆                 ┆            ┆ 100.9008]               ┆ 2024-08-…             │
│ …          ┆ …               ┆ …          ┆ …                       ┆ …                     │
│ praes_unil ┆ s241171213      ┆ 2024-11-24 ┆ [97.2972, 97.2972, …    ┆ [2024-11-24 00:12:00, │
│            ┆                 ┆            ┆ 86.4864]                ┆ 2024-11-…             │
│ praes_unil ┆ s24612711       ┆ 2024-06-30 ┆ [115.3152, 122.5224, …  ┆ [2024-06-30 00:10:00, │
│            ┆                 ┆            ┆ 109.909…                ┆ 2024-06-…             │
│ zhao       ┆ 2046_0_20201216 ┆ 2020-12-25 ┆ [124.2, 124.2, … 124.2] ┆ [2020-12-25 00:05:00, │
│            ┆                 ┆            ┆                         ┆ 2020-12-…             │
│ zhao       ┆ 2001_1_20201117 ┆ 2020-12-01 ┆ [124.2, 124.2, … 180.0] ┆ [2020-12-01 00:04:00, │
│            ┆                 ┆            ┆                         ┆ 2020-12-…             │
│ praes_unil ┆ s24515120       ┆ 2024-08-25 ┆ [88.2882, 88.2882, …    ┆ [2024-08-25 00:02:00, │
│            ┆                 ┆            ┆ 108.108]                ┆ 2024-08-…             │
└────────────┴─────────────────┴────────────┴─────────────────────────┴───────────────────────┘

Taking CGMs around other available information

In [9]:
ubeh = UnifiedFoodData(datasets)
food_df = ubeh.unified_data

In [10]:
ts_manager = TimeSeriesManager(df)  
out = ts_manager.cgms_around_events(
    events_df=food_df,
    event_column="FoodTimepoint",
    patient_identifier_col="Id",
    hour_window=2.0,
)
out.head()

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Id        ┆ food      ┆ FoodTimep ┆ meal      ┆ … ┆ CGMBefore ┆ CGMTimeBe ┆ CGMAfter  ┆ CGMTimeA │
│ ---       ┆ ---       ┆ oint      ┆ ---       ┆   ┆ ---       ┆ fore      ┆ ---       ┆ fter     │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ list[f64] ┆ ---       ┆ list[f64] ┆ ---      │
│           ┆           ┆ datetime[ ┆           ┆   ┆           ┆ list[date ┆           ┆ list[dat │
│           ┆           ┆ μs]       ┆           ┆   ┆           ┆ time[μs]] ┆           ┆ etime[μs │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]]       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s24108114 ┆ ŪDENS,    ┆ 2024-10-1 ┆ Breakfast ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 7         ┆ KRĀNA     ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ŪDENS     ┆ 08:00:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (200 ml). ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ O…        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s24108114 ┆ CŪKGAĻAS  ┆ 2024-10-1 ┆ Lunch     ┆ … ┆ [97.2972, ┆ [2024-10- ┆ [88.2882, ┆ [2024-10 │
│ 7         ┆ KARBONĀDE ┆ 0         ┆           ┆   ┆ 95.4954,  ┆ 10        ┆ 86.4864,  ┆ -10 12:3 │
│           ┆ ,         ┆ 12:30:00  ┆           ┆   ┆ …         ┆ 11:23:00, ┆ …         ┆ 8:00,    │
│           ┆ KOTLETES  ┆           ┆           ┆   ┆ 93.6936]  ┆ 2024-10-… ┆ 97.2972]  ┆ 2024-10- │
│           ┆ (…        ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ s24108114 ┆ LAPU      ┆ 2024-10-1 ┆ Dinner    ┆ … ┆ [79.2792, ┆ [2024-10- ┆ [86.4864, ┆ [2024-10 │
│ 7         ┆ SALĀTI    ┆ 0         ┆           ┆   ┆ 93.6936,  ┆ 10        ┆ 82.8828,  ┆ -10 15:3 │
│           ┆ (100 g).  ┆ 15:30:00  ┆           ┆   ┆ …         ┆ 13:38:00, ┆ … 81.081] ┆ 8:00,    │
│           ┆ LASIS,    ┆           ┆           ┆   ┆ 86.4864]  ┆ 2024-10-… ┆           ┆ 2024-10- │
│           ┆ KĀ…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ s24108114 ┆ ŪDENS,    ┆ 2024-10-1 ┆ Breakfast ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 7         ┆ KRĀNA     ┆ 1 03:20:2 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ŪDENS     ┆ 0.824     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (100 ml)  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s24108114 ┆ TOMĀTI    ┆ 2024-10-1 ┆ Breakfast ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 7         ┆ (250 g)   ┆ 1 06:44:2 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 6.451     ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
ubeh = UnifiedPhysicalActivityData(datasets)
act_df = ubeh.unified_data

In [12]:
act_df

shape: (8_410, 6)
┌────────────┬───────────────┬───────────┬──────────┬─────────────────────┬────────────┐
│ Id         ┆ activity_name ┆ startTime ┆ duration ┆ ActivityTimepoint   ┆ dataset    │
│ ---        ┆ ---           ┆ ---       ┆ ---      ┆ ---                 ┆ ---        │
│ str        ┆ str           ┆ str       ┆ i64      ┆ datetime[μs]        ┆ str        │
╞════════════╪═══════════════╪═══════════╪══════════╪═════════════════════╪════════════╡
│ s241081147 ┆ Walk          ┆ 16:20     ┆ 2099000  ┆ 2024-10-10 16:20:00 ┆ praes_unil │
│ s241081147 ┆ Walk          ┆ 19:16     ┆ 1075000  ┆ 2024-10-10 19:16:00 ┆ praes_unil │
│ s241081147 ┆ Walk          ┆ 20:08     ┆ 1331000  ┆ 2024-10-10 20:08:00 ┆ praes_unil │
│ s241081147 ┆ Walk          ┆ 06:48     ┆ 1485000  ┆ 2024-10-11 06:48:00 ┆ praes_unil │
│ s241081147 ┆ Walk          ┆ 16:50     ┆ 2713000  ┆ 2024-10-11 16:50:00 ┆ praes_unil │
│ …          ┆ …             ┆ …         ┆ …        ┆ …                   ┆ …          │
│ s2512892   ┆ Run           ┆ 19:31     ┆ 3549000  ┆ 2025-06-05 19:31:00 ┆ praes_unil │
│ s2512892   ┆ Walk          ┆ 15:48     ┆ 6450000  ┆ 2025-06-07 15:48:00 ┆ praes_unil │
│ s2512892   ┆ Run           ┆ 10:00     ┆ 3518000  ┆ 2025-06-08 10:00:00 ┆ praes_unil │
│ s2512892   ┆ Walk          ┆ 13:54     ┆ 1894000  ┆ 2025-06-09 13:54:00 ┆ praes_unil │
│ s2512892   ┆ Run           ┆ 19:07     ┆ 2938000  ┆ 2025-06-10 19:07:00 ┆ praes_unil │
└────────────┴───────────────┴───────────┴──────────┴─────────────────────┴────────────┘

In [13]:
out = ts_manager.cgms_around_events(
    events_df=act_df,
    event_column="ActivityTimepoint",
    patient_identifier_col="Id",
    hour_window=2.0,
)
out.head()

shape: (5, 10)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Id        ┆ activity_ ┆ startTime ┆ duration ┆ … ┆ CGMBefore ┆ CGMTimeBe ┆ CGMAfter  ┆ CGMTimeAf │
│ ---       ┆ name      ┆ ---       ┆ ---      ┆   ┆ ---       ┆ fore      ┆ ---       ┆ ter       │
│ str       ┆ ---       ┆ str       ┆ i64      ┆   ┆ list[f64] ┆ ---       ┆ list[f64] ┆ ---       │
│           ┆ str       ┆           ┆          ┆   ┆           ┆ list[date ┆           ┆ list[date │
│           ┆           ┆           ┆          ┆   ┆           ┆ time[μs]] ┆           ┆ time[μs]] │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ s24108114 ┆ Walk      ┆ 16:20     ┆ 2099000  ┆ … ┆ [97.2972, ┆ [2024-10- ┆ [72.072,  ┆ [2024-10- │
│ 7         ┆           ┆           ┆          ┆   ┆ 93.6936,  ┆ 10        ┆ 73.8738,  ┆ 10        │
│           ┆           ┆           ┆          ┆   ┆ …         ┆ 14:23:00, ┆ …         ┆ 16:23:00, │
│           ┆           ┆           ┆          ┆   ┆ 75.6756]  ┆ 2024-10-… ┆ 79.2792]  ┆ 2024-10-… │
│ s24108114 ┆ Walk      ┆ 19:16     ┆ 1075000  ┆ … ┆ [81.081,  ┆ [2024-10- ┆ [72.072,  ┆ [2024-10- │
│ 7         ┆           ┆           ┆          ┆   ┆ 81.081, … ┆ 10        ┆ 77.4774,  ┆ 10        │
│           ┆           ┆           ┆          ┆   ┆ 73.8738]  ┆ 17:23:00, ┆ …         ┆ 19:23:00, │
│           ┆           ┆           ┆          ┆   ┆           ┆ 2024-10-… ┆ 88.2882]  ┆ 2024-10-… │
│ s24108114 ┆ Walk      ┆ 20:08     ┆ 1331000  ┆ … ┆ [79.2792, ┆ [2024-10- ┆ [86.4864, ┆ [2024-10- │
│ 7         ┆           ┆           ┆          ┆   ┆ 81.081, … ┆ 10        ┆ 88.2882,  ┆ 10        │
│           ┆           ┆           ┆          ┆   ┆ 82.8828]  ┆ 18:08:00, ┆ …         ┆ 20:23:00, │
│           ┆           ┆           ┆          ┆   ┆           ┆ 2024-10-… ┆ 91.8918]  ┆ 2024-10-… │
│ s24108114 ┆ Walk      ┆ 06:48     ┆ 1485000  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 7         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ s24108114 ┆ Walk      ┆ 16:50     ┆ 2713000  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 7         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

Running quality checks on the cgm

In [14]:
from chronoindex.glucose_series_processing.cgm_checking_functions import run_all_unified_checks

results = run_all_unified_checks(
    df,
    min_unique_days=7,
    min_records=1000,
)

Running unified CGM checks
- Input shape: rows=185, cols=4
- Grouping key: 'dataset + Id'
- Thresholds: min_unique_days=7, min_records=1000
[1/5] Checking duplicate CGM readings...
No duplicate CGM readings found.
[2/5] Checking null glucose/timestamp values...
Null glucose/timestamp values found for the following subjects:
shape: (5, 5)
┌─────────┬─────────────────┬─────────────────────┬──────────────────┬────────────────────┐
│ dataset ┆ Id              ┆ null_glucose_values ┆ null_time_values ┆ rows_with_any_null │
│ ---     ┆ ---             ┆ ---                 ┆ ---              ┆ ---                │
│ str     ┆ str             ┆ u32                 ┆ u32              ┆ u32                │
╞═════════╪═════════════════╪═════════════════════╪══════════════════╪════════════════════╡
│ zhao    ┆ 2023_0_20210812 ┆ 3                   ┆ 0                ┆ 3                  │
│ zhao    ┆ 2040_0_20210729 ┆ 1                   ┆ 0                ┆ 1                  │
│ zhao    ┆ 2080_0_20210816 ┆ 3                   ┆ 0                ┆ 3                  │
│ zhao    ┆ 2084_0_20211013 ┆ 2                   ┆ 0                ┆ 2                  │
│ zhao    ┆ 2095_0_20201116 ┆ 5                   ┆ 0                ┆ 5                  │
└─────────┴─────────────────┴─────────────────────┴──────────────────┴────────────────────┘
[3/5] Checking minimum unique recording days...
Subjects below the minimum unique recording days threshold found:
shape: (12, 3)
┌─────────┬─────────────────┬─────────────┐
│ dataset ┆ Id              ┆ unique_days │
│ ---     ┆ ---             ┆ ---         │
│ str     ┆ str             ┆ i64         │
╞═════════╪═════════════════╪═════════════╡
│ zhao    ┆ 2004_0_20211028 ┆ 6           │
│ zhao    ┆ 2006_0_20211112 ┆ 6           │
│ zhao    ┆ 2009_0_20211103 ┆ 6           │
│ zhao    ┆ 2011_0_20220123 ┆ 6           │
│ zhao    ┆ 2012_0_20220126 ┆ 4           │
│ …       ┆ …               ┆ …           │
│ zhao    ┆ 2034_0_20210624 ┆ 5           │
│ zhao    ┆ 2035_0_20210629 ┆ 4           │
│ zhao    ┆ 2041_0_20210813 ┆ 5           │
│ zhao    ┆ 2042_0_20211019 ┆ 5           │
│ zhao    ┆ 2054_0_20210524 ┆ 6           │
└─────────┴─────────────────┴─────────────┘
[4/5] Checking minimum number of CGM readings...
Subjects below the minimum CGM readings threshold found:
shape: (40, 3)
┌────────────┬─────────────────┬───────────┐
│ dataset    ┆ Id              ┆ n_records │
│ ---        ┆ ---             ┆ ---       │
│ str        ┆ str             ┆ i64       │
╞════════════╪═════════════════╪═══════════╡
│ praes_unil ┆ s24417854       ┆ 982       │
│ zhao       ┆ 2002_0_20210513 ┆ 571       │
│ zhao       ┆ 2003_0_20210615 ┆ 585       │
│ zhao       ┆ 2004_0_20211028 ┆ 484       │
│ zhao       ┆ 2005_0_20211201 ┆ 691       │
│ …          ┆ …               ┆ …         │
│ zhao       ┆ 2061_0_20210601 ┆ 934       │
│ zhao       ┆ 2065_0_20210615 ┆ 847       │
│ zhao       ┆ 2074_1_20210720 ┆ 978       │
│ zhao       ┆ 2075_0_20210720 ┆ 938       │
│ zhao       ┆ 2084_0_20211013 ┆ 663       │
└────────────┴─────────────────┴───────────┘
[5/5] Checking non-consecutive recording days...
Non-consecutive recording days found for the following subjects:
shape: (76, 3)
┌────────────┬─────────────┬──────────────────────────────┐
│ dataset    ┆ Id          ┆ non_consecutive_day_pairs    │
│ ---        ┆ ---         ┆ ---                          │
│ str        ┆ str         ┆ list[str]                    │
╞════════════╪═════════════╪══════════════════════════════╡
│ praes_unil ┆ s241081147  ┆ ["2024-10-10 -> 2024-12-19"] │
│ praes_unil ┆ s241112738  ┆ ["2024-11-27 -> 2025-01-15"] │
│ praes_unil ┆ s24111587   ┆ ["2024-12-03 -> 2025-01-15"] │
│ praes_unil ┆ s2411191112 ┆ ["2024-12-12 -> 2025-01-29"] │
│ praes_unil ┆ s2411201027 ┆ ["2024-11-28 -> 2025-02-06"] │
│ …          ┆ …           ┆ …                            │
│ praes_unil ┆ s25116633   ┆ ["2025-02-05 -> 2025-03-26"] │
│ praes_unil ┆ s25116857   ┆ ["2025-02-24 -> 2025-04-01"] │
│ praes_unil ┆ s251281327  ┆ ["2025-02-17 -> 2025-04-02"] │
│ praes_unil ┆ s25128853   ┆ ["2025-02-13 -> 2025-04-02"] │
│ praes_unil ┆ s2512892    ┆ ["2025-02-19 -> 2025-04-08"] │
└────────────┴─────────────┴──────────────────────────────┘
Completed unified CGM checks.